
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: C:/LW/bmp/lcd-image-converter/Font_5x7.xml
* name: Font_5x7
* family: MS Shell Dlg 2
* size: 7
* style: Обычный
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюя
* antialiasing: no
* type: monospaced
* encoding: CP1251
* unicode bom: no
*
* preset name: Монохромное
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>
#include "bmp.h"



#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x20[5] = {
    // #####
    // #####
    // #####
    // #####
    // #####
    // #####
    // #####
    0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_5x7_0x20 = { image_data_Font_5x7_0x20,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x21[5] = {
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    // ##∙##
    // #####
    0x21, 0x08, 0x40, 0x10, 0x00
};
static const tImage Font_5x7_0x21 = { image_data_Font_5x7_0x21,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x22[5] = {
    // #####
    // #∙#∙#
    // #####
    // #####
    // #####
    // #####
    // #####
    0x02, 0x80, 0x00, 0x00, 0x00
};
static const tImage Font_5x7_0x22 = { image_data_Font_5x7_0x22,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x23[5] = {
    // #####
    // #∙#∙#
    // ∙∙∙∙∙
    // #∙#∙#
    // ∙∙∙∙∙
    // #∙#∙#
    // #####
    0x02, 0xbe, 0xaf, 0xa8, 0x00
};
static const tImage Font_5x7_0x23 = { image_data_Font_5x7_0x23,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x24[5] = {
    // ##∙##
    // #∙∙∙∙
    // ∙#∙##
    // #∙∙∙#
    // ##∙#∙
    // ∙∙∙∙#
    // ##∙##
    0x23, 0xe8, 0xe2, 0xf8, 0x80
};
static const tImage Font_5x7_0x24 = { image_data_Font_5x7_0x24,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x25[5] = {
    // #####
    // ∙##∙#
    // ###∙#
    // ##∙##
    // #∙###
    // #∙##∙
    // #####
    0x04, 0x84, 0x44, 0x24, 0x00
};
static const tImage Font_5x7_0x25 = { image_data_Font_5x7_0x25,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x26[5] = {
    // #####
    // ##∙##
    // #∙#∙#
    // ##∙##
    // #∙∙#∙
    // ∙##∙#
    // #∙∙#∙
    0x01, 0x14, 0x46, 0xc9, 0xa0
};
static const tImage Font_5x7_0x26 = { image_data_Font_5x7_0x26,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x27[5] = {
    // #####
    // ##∙##
    // ##∙##
    // #####
    // #####
    // #####
    // #####
    0x01, 0x08, 0x00, 0x00, 0x00
};
static const tImage Font_5x7_0x27 = { image_data_Font_5x7_0x27,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x28[5] = {
    // ##∙##
    // #∙###
    // #∙###
    // #∙###
    // #∙###
    // ##∙##
    // #####
    0x22, 0x10, 0x84, 0x10, 0x00
};
static const tImage Font_5x7_0x28 = { image_data_Font_5x7_0x28,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x29[5] = {
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0x21, 0x08, 0x42, 0x10, 0x00
};
static const tImage Font_5x7_0x29 = { image_data_Font_5x7_0x29,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x2a[5] = {
    // #####
    // #∙#∙#
    // ##∙##
    // #∙#∙#
    // #####
    // #####
    // #####
    0x02, 0x88, 0xa0, 0x00, 0x00
};
static const tImage Font_5x7_0x2a = { image_data_Font_5x7_0x2a,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x2b[5] = {
    // #####
    // #####
    // ##∙##
    // #∙∙∙#
    // ##∙##
    // #####
    // #####
    0x00, 0x08, 0xe2, 0x00, 0x00
};
static const tImage Font_5x7_0x2b = { image_data_Font_5x7_0x2b,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x2c[5] = {
    // #####
    // #####
    // #####
    // #####
    // #####
    // ##∙##
    // ##∙##
    0x00, 0x00, 0x00, 0x10, 0x80
};
static const tImage Font_5x7_0x2c = { image_data_Font_5x7_0x2c,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x2d[5] = {
    // #####
    // #####
    // #####
    // #∙∙∙#
    // #####
    // #####
    // #####
    0x00, 0x00, 0xe0, 0x00, 0x00
};
static const tImage Font_5x7_0x2d = { image_data_Font_5x7_0x2d,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x2e[5] = {
    // #####
    // #####
    // #####
    // #####
    // #####
    // ##∙##
    // #####
    0x00, 0x00, 0x00, 0x10, 0x00
};
static const tImage Font_5x7_0x2e = { image_data_Font_5x7_0x2e,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x2f[5] = {
    // ###∙#
    // ###∙#
    // ##∙##
    // ##∙##
    // #∙###
    // #∙###
    // #####
    0x10, 0x88, 0x44, 0x20, 0x00
};
static const tImage Font_5x7_0x2f = { image_data_Font_5x7_0x2f,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x30[5] = {
    // ##∙∙#
    // #∙##∙
    // #∙∙#∙
    // #∙#∙∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x32, 0x5a, 0xb4, 0x98, 0x00
};
static const tImage Font_5x7_0x30 = { image_data_Font_5x7_0x30,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x31[5] = {
    // ###∙#
    // ##∙∙#
    // ###∙#
    // ###∙#
    // ###∙#
    // ##∙∙∙
    // #####
    0x11, 0x84, 0x21, 0x1c, 0x00
};
static const tImage Font_5x7_0x31 = { image_data_Font_5x7_0x31,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x32[5] = {
    // ##∙∙#
    // #∙##∙
    // ####∙
    // ###∙#
    // ##∙##
    // #∙∙∙∙
    // #####
    0x32, 0x42, 0x22, 0x3c, 0x00
};
static const tImage Font_5x7_0x32 = { image_data_Font_5x7_0x32,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x33[5] = {
    // #∙∙∙∙
    // ####∙
    // ##∙∙∙
    // ####∙
    // ####∙
    // #∙∙∙∙
    // #####
    0x78, 0x4e, 0x10, 0xbc, 0x00
};
static const tImage Font_5x7_0x33 = { image_data_Font_5x7_0x33,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x34[5] = {
    // ###∙∙
    // ##∙#∙
    // #∙##∙
    // #∙∙∙∙
    // ####∙
    // ####∙
    // #####
    0x19, 0x52, 0xf0, 0x84, 0x00
};
static const tImage Font_5x7_0x34 = { image_data_Font_5x7_0x34,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x35[5] = {
    // #∙∙∙∙
    // #∙###
    // ##∙∙#
    // ####∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x7a, 0x0c, 0x14, 0x98, 0x00
};
static const tImage Font_5x7_0x35 = { image_data_Font_5x7_0x35,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x36[5] = {
    // ##∙∙∙
    // #∙###
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x3a, 0x1c, 0x94, 0x98, 0x00
};
static const tImage Font_5x7_0x36 = { image_data_Font_5x7_0x36,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x37[5] = {
    // #∙∙∙∙
    // ####∙
    // ###∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0x78, 0x44, 0x42, 0x10, 0x00
};
static const tImage Font_5x7_0x37 = { image_data_Font_5x7_0x37,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x38[5] = {
    // ##∙∙#
    // #∙##∙
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x32, 0x4c, 0x94, 0x98, 0x00
};
static const tImage Font_5x7_0x38 = { image_data_Font_5x7_0x38,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x39[5] = {
    // ##∙∙#
    // #∙##∙
    // ##∙∙∙
    // ####∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x32, 0x4e, 0x14, 0x98, 0x00
};
static const tImage Font_5x7_0x39 = { image_data_Font_5x7_0x39,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x3a[5] = {
    // #####
    // ##∙##
    // #####
    // #####
    // ##∙##
    // #####
    // #####
    0x01, 0x00, 0x02, 0x00, 0x00
};
static const tImage Font_5x7_0x3a = { image_data_Font_5x7_0x3a,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x3b[5] = {
    // #####
    // ###∙#
    // #####
    // #####
    // ###∙#
    // ##∙##
    // #####
    0x00, 0x80, 0x01, 0x10, 0x00
};
static const tImage Font_5x7_0x3b = { image_data_Font_5x7_0x3b,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x3c[5] = {
    // #####
    // ###∙#
    // ##∙##
    // #∙###
    // ##∙##
    // ###∙#
    // #####
    0x00, 0x88, 0x82, 0x08, 0x00
};
static const tImage Font_5x7_0x3c = { image_data_Font_5x7_0x3c,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x3d[5] = {
    // #####
    // #####
    // #∙∙∙#
    // #####
    // #∙∙∙#
    // #####
    // #####
    0x00, 0x1c, 0x07, 0x00, 0x00
};
static const tImage Font_5x7_0x3d = { image_data_Font_5x7_0x3d,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x3e[5] = {
    // #####
    // #∙###
    // ##∙##
    // ###∙#
    // ##∙##
    // #∙###
    // #####
    0x02, 0x08, 0x22, 0x20, 0x00
};
static const tImage Font_5x7_0x3e = { image_data_Font_5x7_0x3e,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x3f[5] = {
    // #∙∙∙#
    // ###∙#
    // ##∙##
    // ##∙##
    // #####
    // ##∙##
    // #####
    0x70, 0x88, 0x40, 0x10, 0x00
};
static const tImage Font_5x7_0x3f = { image_data_Font_5x7_0x3f,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x40[5] = {
    // #∙∙∙#
    // ∙###∙
    // ##∙#∙
    // #∙#∙∙
    // ##∙∙#
    // ∙####
    // #∙∙∙∙
    0x74, 0x4a, 0xb3, 0x41, 0xe0
};
static const tImage Font_5x7_0x40 = { image_data_Font_5x7_0x40,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x41[5] = {
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #####
    0x32, 0x52, 0xf4, 0xa4, 0x00
};
static const tImage Font_5x7_0x41 = { image_data_Font_5x7_0x41,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x42[5] = {
    // #∙∙∙#
    // #∙##∙
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #####
    0x72, 0x5c, 0x94, 0xb8, 0x00
};
static const tImage Font_5x7_0x42 = { image_data_Font_5x7_0x42,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x43[5] = {
    // ##∙∙#
    // #∙##∙
    // #∙###
    // #∙###
    // #∙##∙
    // ##∙∙#
    // #####
    0x32, 0x50, 0x84, 0x98, 0x00
};
static const tImage Font_5x7_0x43 = { image_data_Font_5x7_0x43,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x44[5] = {
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #####
    0x72, 0x52, 0x94, 0xb8, 0x00
};
static const tImage Font_5x7_0x44 = { image_data_Font_5x7_0x44,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x45[5] = {
    // #∙∙∙∙
    // #∙###
    // #∙∙∙#
    // #∙###
    // #∙###
    // #∙∙∙∙
    // #####
    0x7a, 0x1c, 0x84, 0x3c, 0x00
};
static const tImage Font_5x7_0x45 = { image_data_Font_5x7_0x45,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x46[5] = {
    // #∙∙∙∙
    // #∙###
    // #∙∙∙#
    // #∙###
    // #∙###
    // #∙###
    // #####
    0x7a, 0x1c, 0x84, 0x20, 0x00
};
static const tImage Font_5x7_0x46 = { image_data_Font_5x7_0x46,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x47[5] = {
    // ##∙∙∙
    // #∙###
    // #∙###
    // #∙#∙∙
    // #∙##∙
    // ##∙∙∙
    // #####
    0x3a, 0x10, 0xb4, 0x9c, 0x00
};
static const tImage Font_5x7_0x47 = { image_data_Font_5x7_0x47,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x48[5] = {
    // #∙##∙
    // #∙##∙
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #####
    0x4a, 0x5e, 0x94, 0xa4, 0x00
};
static const tImage Font_5x7_0x48 = { image_data_Font_5x7_0x48,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x49[5] = {
    // #∙∙∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #∙∙∙#
    // #####
    0x71, 0x08, 0x42, 0x38, 0x00
};
static const tImage Font_5x7_0x49 = { image_data_Font_5x7_0x49,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x4a[5] = {
    // #∙∙∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #∙###
    0x71, 0x08, 0x42, 0x11, 0x00
};
static const tImage Font_5x7_0x4a = { image_data_Font_5x7_0x4a,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x4b[5] = {
    // #∙##∙
    // #∙#∙#
    // #∙∙##
    // #∙#∙#
    // #∙#∙#
    // #∙##∙
    // #####
    0x4a, 0x98, 0xa5, 0x24, 0x00
};
static const tImage Font_5x7_0x4b = { image_data_Font_5x7_0x4b,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x4c[5] = {
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙∙∙
    // #####
    0x21, 0x08, 0x42, 0x1c, 0x00
};
static const tImage Font_5x7_0x4c = { image_data_Font_5x7_0x4c,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x4d[5] = {
    // #####
    // ∙###∙
    // ∙∙#∙∙
    // ∙#∙#∙
    // ∙###∙
    // ∙###∙
    // #####
    0x04, 0x77, 0x58, 0xc4, 0x00
};
static const tImage Font_5x7_0x4d = { image_data_Font_5x7_0x4d,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x4e[5] = {
    // #∙##∙
    // #∙∙#∙
    // #∙∙#∙
    // #∙#∙∙
    // #∙#∙∙
    // #∙##∙
    // #####
    0x4b, 0x5a, 0xb5, 0xa4, 0x00
};
static const tImage Font_5x7_0x4e = { image_data_Font_5x7_0x4e,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x4f[5] = {
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x32, 0x52, 0x94, 0x98, 0x00
};
static const tImage Font_5x7_0x4f = { image_data_Font_5x7_0x4f,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x50[5] = {
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #∙###
    // #∙###
    // #####
    0x72, 0x52, 0xe4, 0x20, 0x00
};
static const tImage Font_5x7_0x50 = { image_data_Font_5x7_0x50,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x51[5] = {
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // ###∙∙
    0x32, 0x52, 0x94, 0x98, 0x60
};
static const tImage Font_5x7_0x51 = { image_data_Font_5x7_0x51,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x52[5] = {
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #####
    0x72, 0x52, 0xe4, 0xa4, 0x00
};
static const tImage Font_5x7_0x52 = { image_data_Font_5x7_0x52,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x53[5] = {
    // ##∙∙∙
    // #∙###
    // ##∙∙#
    // ####∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x3a, 0x0c, 0x14, 0x98, 0x00
};
static const tImage Font_5x7_0x53 = { image_data_Font_5x7_0x53,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x54[5] = {
    // ∙∙∙∙∙
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0xf9, 0x08, 0x42, 0x10, 0x00
};
static const tImage Font_5x7_0x54 = { image_data_Font_5x7_0x54,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x55[5] = {
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // #####
    0x4a, 0x52, 0x94, 0x9c, 0x00
};
static const tImage Font_5x7_0x55 = { image_data_Font_5x7_0x55,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x56[5] = {
    // ∙###∙
    // ∙###∙
    // ∙###∙
    // #∙#∙#
    // #∙#∙#
    // ##∙##
    // #####
    0x8c, 0x62, 0xa5, 0x10, 0x00
};
static const tImage Font_5x7_0x56 = { image_data_Font_5x7_0x56,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x57[5] = {
    // ∙###∙
    // ∙###∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // #∙#∙#
    // #####
    0x8c, 0x6b, 0x5a, 0xa8, 0x00
};
static const tImage Font_5x7_0x57 = { image_data_Font_5x7_0x57,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x58[5] = {
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #####
    0x4a, 0x4c, 0x64, 0xa4, 0x00
};
static const tImage Font_5x7_0x58 = { image_data_Font_5x7_0x58,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x59[5] = {
    // ∙###∙
    // #∙#∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0x8a, 0x88, 0x42, 0x10, 0x00
};
static const tImage Font_5x7_0x59 = { image_data_Font_5x7_0x59,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x5a[5] = {
    // #∙∙∙∙
    // ####∙
    // ###∙#
    // ##∙##
    // #∙###
    // #∙∙∙∙
    // #####
    0x78, 0x44, 0x44, 0x3c, 0x00
};
static const tImage Font_5x7_0x5a = { image_data_Font_5x7_0x5a,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x5b[5] = {
    // ##∙∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙∙#
    // #####
    0x31, 0x08, 0x42, 0x18, 0x00
};
static const tImage Font_5x7_0x5b = { image_data_Font_5x7_0x5b,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x5c[5] = {
    // #∙###
    // #∙###
    // ##∙##
    // ##∙##
    // ###∙#
    // ###∙#
    // #####
    0x42, 0x08, 0x41, 0x08, 0x00
};
static const tImage Font_5x7_0x5c = { image_data_Font_5x7_0x5c,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x5d[5] = {
    // #∙∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #∙∙##
    // #####
    0x61, 0x08, 0x42, 0x30, 0x00
};
static const tImage Font_5x7_0x5d = { image_data_Font_5x7_0x5d,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x5e[5] = {
    // #####
    // ##∙##
    // #∙#∙#
    // ∙###∙
    // #####
    // #####
    // #####
    0x01, 0x15, 0x10, 0x00, 0x00
};
static const tImage Font_5x7_0x5e = { image_data_Font_5x7_0x5e,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x5f[5] = {
    // #####
    // #####
    // #####
    // #####
    // #####
    // #∙∙∙∙
    // #####
    0x00, 0x00, 0x00, 0x3c, 0x00
};
static const tImage Font_5x7_0x5f = { image_data_Font_5x7_0x5f,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x60[5] = {
    // #∙###
    // ##∙##
    // #####
    // #####
    // #####
    // #####
    // #####
    0x41, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_5x7_0x60 = { image_data_Font_5x7_0x60,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x61[5] = {
    // #####
    // ##∙∙∙
    // ####∙
    // ##∙∙∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x01, 0xc2, 0x74, 0x98, 0x00
};
static const tImage Font_5x7_0x61 = { image_data_Font_5x7_0x61,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x62[5] = {
    // #####
    // #∙###
    // #∙∙##
    // #∙#∙#
    // #∙#∙#
    // #∙∙##
    // #####
    0x02, 0x18, 0xa5, 0x30, 0x00
};
static const tImage Font_5x7_0x62 = { image_data_Font_5x7_0x62,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x63[5] = {
    // #####
    // ##∙∙#
    // #∙###
    // #∙###
    // #∙###
    // ##∙∙#
    // #####
    0x01, 0x90, 0x84, 0x18, 0x00
};
static const tImage Font_5x7_0x63 = { image_data_Font_5x7_0x63,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x64[5] = {
    // #####
    // ###∙#
    // ##∙∙#
    // #∙#∙#
    // #∙#∙#
    // ##∙∙#
    // #####
    0x00, 0x8c, 0xa5, 0x18, 0x00
};
static const tImage Font_5x7_0x64 = { image_data_Font_5x7_0x64,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x65[5] = {
    // #####
    // ##∙∙#
    // #∙##∙
    // #∙∙∙#
    // #∙###
    // ##∙∙#
    // #####
    0x01, 0x92, 0xe4, 0x18, 0x00
};
static const tImage Font_5x7_0x65 = { image_data_Font_5x7_0x65,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x66[5] = {
    // ###∙#
    // ##∙##
    // ##∙##
    // #∙∙∙#
    // ##∙##
    // ##∙##
    // #####
    0x11, 0x08, 0xe2, 0x10, 0x00
};
static const tImage Font_5x7_0x66 = { image_data_Font_5x7_0x66,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x67[5] = {
    // #####
    // ##∙∙#
    // #∙#∙#
    // #∙#∙#
    // ##∙∙#
    // ###∙#
    // #∙∙∙#
    0x01, 0x94, 0xa3, 0x09, 0xc0
};
static const tImage Font_5x7_0x67 = { image_data_Font_5x7_0x67,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x68[5] = {
    // #####
    // #∙###
    // #∙∙##
    // #∙#∙#
    // #∙#∙#
    // #∙#∙#
    // #####
    0x02, 0x18, 0xa5, 0x28, 0x00
};
static const tImage Font_5x7_0x68 = { image_data_Font_5x7_0x68,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x69[5] = {
    // ##∙##
    // #####
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0x20, 0x08, 0x42, 0x10, 0x00
};
static const tImage Font_5x7_0x69 = { image_data_Font_5x7_0x69,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x6a[5] = {
    // ##∙##
    // #####
    // ##∙##
    // ##∙##
    // ##∙##
    // #∙###
    // #####
    0x20, 0x08, 0x42, 0x20, 0x00
};
static const tImage Font_5x7_0x6a = { image_data_Font_5x7_0x6a,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x6b[5] = {
    // #####
    // #∙###
    // #∙#∙#
    // #∙∙##
    // #∙#∙#
    // #∙#∙#
    // #####
    0x02, 0x14, 0xc5, 0x28, 0x00
};
static const tImage Font_5x7_0x6b = { image_data_Font_5x7_0x6b,
    5, 7};
#endif

#if (0x029 == 0x0)
static const uint8_t image_data_Font_5x7_0x6c[5] = {
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0x21, 0x08, 0x42, 0x10, 0x00
};
static const tImage Font_5x7_0x6c = { image_data_Font_5x7_0x6c,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x6d[5] = {
    // #####
    // ∙∙∙∙#
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // #####
    0x07, 0xab, 0x5a, 0xd4, 0x00
};
static const tImage Font_5x7_0x6d = { image_data_Font_5x7_0x6d,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x6e[5] = {
    // #####
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #####
    0x03, 0x92, 0x94, 0xa4, 0x00
};
static const tImage Font_5x7_0x6e = { image_data_Font_5x7_0x6e,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x6f[5] = {
    // #####
    // #####
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x00, 0x0c, 0x94, 0x98, 0x00
};
static const tImage Font_5x7_0x6f = { image_data_Font_5x7_0x6f,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x70[5] = {
    // #####
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #∙###
    // #####
    0x03, 0x92, 0x97, 0x20, 0x00
};
static const tImage Font_5x7_0x70 = { image_data_Font_5x7_0x70,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x71[5] = {
    // #####
    // ##∙∙#
    // #∙#∙#
    // #∙#∙#
    // ##∙∙#
    // ###∙#
    // ###∙#
    0x01, 0x94, 0xa3, 0x08, 0x40
};
static const tImage Font_5x7_0x71 = { image_data_Font_5x7_0x71,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x72[5] = {
    // #####
    // #∙#∙#
    // #∙∙##
    // #∙###
    // #∙###
    // #∙###
    // #####
    0x02, 0x98, 0x84, 0x20, 0x00
};
static const tImage Font_5x7_0x72 = { image_data_Font_5x7_0x72,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x73[5] = {
    // #####
    // ##∙∙∙
    // #∙###
    // ##∙∙#
    // ####∙
    // #∙∙∙#
    // #####
    0x01, 0xd0, 0x60, 0xb8, 0x00
};
static const tImage Font_5x7_0x73 = { image_data_Font_5x7_0x73,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x74[5] = {
    // ##∙##
    // #∙∙∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙∙#
    // #####
    0x23, 0x88, 0x42, 0x18, 0x00
};
static const tImage Font_5x7_0x74 = { image_data_Font_5x7_0x74,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x75[5] = {
    // #####
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // #####
    0x02, 0x52, 0x94, 0x9c, 0x00
};
static const tImage Font_5x7_0x75 = { image_data_Font_5x7_0x75,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x76[5] = {
    // #####
    // #∙#∙#
    // #∙#∙#
    // #∙#∙#
    // ##∙##
    // ##∙##
    // #####
    0x02, 0x94, 0xa2, 0x10, 0x00
};
static const tImage Font_5x7_0x76 = { image_data_Font_5x7_0x76,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x77[5] = {
    // #####
    // ∙###∙
    // ∙#∙#∙
    // ∙#∙#∙
    // #∙#∙#
    // #∙#∙#
    // #####
    0x04, 0x6b, 0x55, 0x28, 0x00
};
static const tImage Font_5x7_0x77 = { image_data_Font_5x7_0x77,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x78[5] = {
    // #####
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #####
    0x02, 0x52, 0x64, 0xa4, 0x00
};
static const tImage Font_5x7_0x78 = { image_data_Font_5x7_0x78,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x79[5] = {
    // #####
    // #####
    // #∙#∙#
    // #∙#∙#
    // ##∙##
    // ##∙##
    // #∙∙##
    0x00, 0x14, 0xa2, 0x11, 0x80
};
static const tImage Font_5x7_0x79 = { image_data_Font_5x7_0x79,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x7a[5] = {
    // #####
    // #∙∙∙∙
    // ###∙#
    // ##∙##
    // #∙###
    // #∙∙∙∙
    // #####
    0x03, 0xc4, 0x44, 0x3c, 0x00
};
static const tImage Font_5x7_0x7a = { image_data_Font_5x7_0x7a,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x7b[5] = {
    // ##∙∙#
    // ##∙##
    // ##∙##
    // #∙###
    // ##∙##
    // ##∙##
    // ##∙∙#
    0x31, 0x08, 0x82, 0x10, 0xc0
};
static const tImage Font_5x7_0x7b = { image_data_Font_5x7_0x7b,
    5, 7};
#endif

#if (0x029 == 0x0)
static const uint8_t image_data_Font_5x7_0x7c[5] = {
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0x21, 0x08, 0x42, 0x10, 0x00
};
static const tImage Font_5x7_0x7c = { image_data_Font_5x7_0x7c,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x7d[5] = {
    // #∙∙##
    // ##∙##
    // ##∙##
    // ###∙#
    // ##∙##
    // ##∙##
    // #∙∙##
    0x61, 0x08, 0x22, 0x11, 0x80
};
static const tImage Font_5x7_0x7d = { image_data_Font_5x7_0x7d,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0x7e[5] = {
    // #####
    // #####
    // #####
    // ##∙#∙
    // #∙#∙#
    // #####
    // #####
    0x00, 0x00, 0x55, 0x00, 0x00
};
static const tImage Font_5x7_0x7e = { image_data_Font_5x7_0x7e,
    5, 7};
#endif

#if (0x041 == 0x0)
static const uint8_t image_data_Font_5x7_0xc0[5] = {
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #####
    0x32, 0x52, 0xf4, 0xa4, 0x00
};
static const tImage Font_5x7_0xc0 = { image_data_Font_5x7_0xc0,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xc1[5] = {
    // #∙∙∙∙
    // #∙###
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙∙∙∙
    // #####
    0x7a, 0x1e, 0x94, 0xbc, 0x00
};
static const tImage Font_5x7_0xc1 = { image_data_Font_5x7_0xc1,
    5, 7};
#endif

#if (0x042 == 0x0)
static const uint8_t image_data_Font_5x7_0xc2[5] = {
    // #∙∙∙#
    // #∙##∙
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #####
    0x72, 0x5c, 0x94, 0xb8, 0x00
};
static const tImage Font_5x7_0xc2 = { image_data_Font_5x7_0xc2,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xc3[5] = {
    // #∙∙∙#
    // #∙###
    // #∙###
    // #∙###
    // #∙###
    // #∙###
    // #####
    0x72, 0x10, 0x84, 0x20, 0x00
};
static const tImage Font_5x7_0xc3 = { image_data_Font_5x7_0xc3,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xc4[5] = {
    // ##∙∙#
    // #∙#∙#
    // #∙#∙#
    // #∙#∙#
    // #∙#∙#
    // ∙∙∙∙∙
    // ∙###∙
    0x32, 0x94, 0xa5, 0x7e, 0x20
};
static const tImage Font_5x7_0xc4 = { image_data_Font_5x7_0xc4,
    5, 7};
#endif

#if (0x045 == 0x0)
static const uint8_t image_data_Font_5x7_0xc5[5] = {
    // #∙∙∙∙
    // #∙###
    // #∙∙∙#
    // #∙###
    // #∙###
    // #∙∙∙∙
    // #####
    0x7a, 0x1c, 0x84, 0x3c, 0x00
};
static const tImage Font_5x7_0xc5 = { image_data_Font_5x7_0xc5,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xc6[5] = {
    // ∙#∙#∙
    // #∙∙∙#
    // ##∙##
    // ##∙##
    // #∙∙∙#
    // ∙#∙#∙
    // #####
    0xab, 0x88, 0x47, 0x54, 0x00
};
static const tImage Font_5x7_0xc6 = { image_data_Font_5x7_0xc6,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xc7[5] = {
    // #∙∙∙#
    // ####∙
    // ##∙∙#
    // ####∙
    // ####∙
    // #∙∙∙#
    // #####
    0x70, 0x4c, 0x10, 0xb8, 0x00
};
static const tImage Font_5x7_0xc7 = { image_data_Font_5x7_0xc7,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xc8[5] = {
    // #∙##∙
    // #∙#∙∙
    // #∙#∙∙
    // #∙∙#∙
    // #∙∙#∙
    // #∙##∙
    // #####
    0x4a, 0xd6, 0xd6, 0xa4, 0x00
};
static const tImage Font_5x7_0xc8 = { image_data_Font_5x7_0xc8,
    5, 7};
#endif

#if (0x0c8 == 0x0)
static const uint8_t image_data_Font_5x7_0xc9[5] = {
    // #∙##∙
    // #∙#∙∙
    // #∙#∙∙
    // #∙∙#∙
    // #∙∙#∙
    // #∙##∙
    // #####
    0x4a, 0xd6, 0xd6, 0xa4, 0x00
};
static const tImage Font_5x7_0xc9 = { image_data_Font_5x7_0xc9,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xca[5] = {
    // #∙##∙
    // #∙#∙#
    // #∙∙##
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #####
    0x4a, 0x98, 0xe4, 0xa4, 0x00
};
static const tImage Font_5x7_0xca = { image_data_Font_5x7_0xca,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xcb[5] = {
    // ##∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ∙###∙
    // #####
    0x3a, 0x52, 0x94, 0xc4, 0x00
};
static const tImage Font_5x7_0xcb = { image_data_Font_5x7_0xcb,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xcc[5] = {
    // ∙###∙
    // ∙∙#∙∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙###∙
    // ∙###∙
    // #####
    0x8e, 0xeb, 0x58, 0xc4, 0x00
};
static const tImage Font_5x7_0xcc = { image_data_Font_5x7_0xcc,
    5, 7};
#endif

#if (0x048 == 0x0)
static const uint8_t image_data_Font_5x7_0xcd[5] = {
    // #∙##∙
    // #∙##∙
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #####
    0x4a, 0x5e, 0x94, 0xa4, 0x00
};
static const tImage Font_5x7_0xcd = { image_data_Font_5x7_0xcd,
    5, 7};
#endif

#if (0x04f == 0x0)
static const uint8_t image_data_Font_5x7_0xce[5] = {
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x32, 0x52, 0x94, 0x98, 0x00
};
static const tImage Font_5x7_0xce = { image_data_Font_5x7_0xce,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xcf[5] = {
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #####
    0x7a, 0x52, 0x94, 0xa4, 0x00
};
static const tImage Font_5x7_0xcf = { image_data_Font_5x7_0xcf,
    5, 7};
#endif

#if (0x050 == 0x0)
static const uint8_t image_data_Font_5x7_0xd0[5] = {
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #∙###
    // #∙###
    // #####
    0x72, 0x52, 0xe4, 0x20, 0x00
};
static const tImage Font_5x7_0xd0 = { image_data_Font_5x7_0xd0,
    5, 7};
#endif

#if (0x043 == 0x0)
static const uint8_t image_data_Font_5x7_0xd1[5] = {
    // ##∙∙#
    // #∙##∙
    // #∙###
    // #∙###
    // #∙##∙
    // ##∙∙#
    // #####
    0x32, 0x50, 0x84, 0x98, 0x00
};
static const tImage Font_5x7_0xd1 = { image_data_Font_5x7_0xd1,
    5, 7};
#endif

#if (0x054 == 0x0)
static const uint8_t image_data_Font_5x7_0xd2[5] = {
    // ∙∙∙∙∙
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0xf9, 0x08, 0x42, 0x10, 0x00
};
static const tImage Font_5x7_0xd2 = { image_data_Font_5x7_0xd2,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xd3[5] = {
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // ####∙
    // #∙##∙
    // ##∙∙#
    0x4a, 0x52, 0x70, 0xa4, 0xc0
};
static const tImage Font_5x7_0xd3 = { image_data_Font_5x7_0xd3,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xd4[5] = {
    // ##∙##
    // #∙∙∙#
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // #∙∙∙#
    // ##∙##
    0x23, 0xab, 0x5a, 0xb8, 0x80
};
static const tImage Font_5x7_0xd4 = { image_data_Font_5x7_0xd4,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xd5[5] = {
    // ∙###∙
    // #∙#∙#
    // ##∙##
    // ##∙##
    // #∙#∙#
    // ∙###∙
    // #####
    0x8a, 0x88, 0x45, 0x44, 0x00
};
static const tImage Font_5x7_0xd5 = { image_data_Font_5x7_0xd5,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xd6[5] = {
    // #∙#∙#
    // #∙#∙#
    // #∙#∙#
    // #∙#∙#
    // #∙#∙#
    // #∙∙∙∙
    // ####∙
    0x52, 0x94, 0xa5, 0x3c, 0x20
};
static const tImage Font_5x7_0xd6 = { image_data_Font_5x7_0xd6,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xd7[5] = {
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // ####∙
    // ####∙
    // #####
    0x4a, 0x52, 0x70, 0x84, 0x00
};
static const tImage Font_5x7_0xd7 = { image_data_Font_5x7_0xd7,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xd8[5] = {
    // ∙###∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙∙∙∙∙
    // #####
    0x8d, 0x6b, 0x5a, 0xfc, 0x00
};
static const tImage Font_5x7_0xd8 = { image_data_Font_5x7_0xd8,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xd9[5] = {
    // ∙###∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙∙∙∙∙
    // ####∙
    0x8d, 0x6b, 0x5a, 0xfc, 0x20
};
static const tImage Font_5x7_0xd9 = { image_data_Font_5x7_0xd9,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xda[5] = {
    // ∙∙###
    // #∙###
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #####
    0xc2, 0x1c, 0x94, 0xb8, 0x00
};
static const tImage Font_5x7_0xda = { image_data_Font_5x7_0xda,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xdb[5] = {
    // ∙###∙
    // ∙###∙
    // ∙∙∙#∙
    // ∙##∙∙
    // ∙##∙∙
    // ∙∙∙#∙
    // #####
    0x8c, 0x7b, 0x39, 0xf4, 0x00
};
static const tImage Font_5x7_0xdb = { image_data_Font_5x7_0xdb,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xdc[5] = {
    // #∙###
    // #∙###
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #####
    0x42, 0x1c, 0x94, 0xb8, 0x00
};
static const tImage Font_5x7_0xdc = { image_data_Font_5x7_0xdc,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xdd[5] = {
    // #∙∙∙#
    // ####∙
    // ##∙∙∙
    // ####∙
    // ####∙
    // #∙∙∙#
    // #####
    0x70, 0x4e, 0x10, 0xb8, 0x00
};
static const tImage Font_5x7_0xdd = { image_data_Font_5x7_0xdd,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xde[5] = {
    // ∙#∙∙∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙∙∙#∙
    // ∙#∙#∙
    // ∙#∙∙∙
    // #####
    0xbd, 0x6b, 0xda, 0xdc, 0x00
};
static const tImage Font_5x7_0xde = { image_data_Font_5x7_0xde,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xdf[5] = {
    // ##∙∙∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // ##∙#∙
    // #∙##∙
    // #####
    0x3a, 0x52, 0x72, 0xa4, 0x00
};
static const tImage Font_5x7_0xdf = { image_data_Font_5x7_0xdf,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xe0[5] = {
    // #####
    // #∙∙∙#
    // ####∙
    // ##∙∙∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x03, 0x82, 0x74, 0x98, 0x00
};
static const tImage Font_5x7_0xe0 = { image_data_Font_5x7_0xe0,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xe1[5] = {
    // ###∙∙
    // ##∙##
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x19, 0x1c, 0x94, 0x98, 0x00
};
static const tImage Font_5x7_0xe1 = { image_data_Font_5x7_0xe1,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xe2[5] = {
    // #####
    // #∙∙∙#
    // #∙##∙
    // #∙∙∙#
    // #∙##∙
    // #∙∙∙#
    // #####
    0x03, 0x92, 0xe4, 0xb8, 0x00
};
static const tImage Font_5x7_0xe2 = { image_data_Font_5x7_0xe2,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xe3[5] = {
    // #####
    // #∙∙∙#
    // #∙###
    // #∙###
    // #∙###
    // #∙###
    // #####
    0x03, 0x90, 0x84, 0x20, 0x00
};
static const tImage Font_5x7_0xe3 = { image_data_Font_5x7_0xe3,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xe4[5] = {
    // #####
    // ###∙∙
    // ##∙#∙
    // ##∙#∙
    // ##∙#∙
    // #∙∙∙∙
    // #∙##∙
    0x00, 0xca, 0x52, 0xbd, 0x20
};
static const tImage Font_5x7_0xe4 = { image_data_Font_5x7_0xe4,
    5, 7};
#endif

#if (0x065 == 0x0)
static const uint8_t image_data_Font_5x7_0xe5[5] = {
    // #####
    // ##∙∙#
    // #∙##∙
    // #∙∙∙#
    // #∙###
    // ##∙∙#
    // #####
    0x01, 0x92, 0xe4, 0x18, 0x00
};
static const tImage Font_5x7_0xe5 = { image_data_Font_5x7_0xe5,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xe6[5] = {
    // #####
    // ∙#∙#∙
    // #∙∙∙#
    // ##∙##
    // #∙∙∙#
    // ∙#∙#∙
    // #####
    0x05, 0x5c, 0x47, 0x54, 0x00
};
static const tImage Font_5x7_0xe6 = { image_data_Font_5x7_0xe6,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xe7[5] = {
    // #####
    // ##∙∙#
    // ####∙
    // ###∙#
    // ####∙
    // ##∙∙#
    // #####
    0x01, 0x82, 0x20, 0x98, 0x00
};
static const tImage Font_5x7_0xe7 = { image_data_Font_5x7_0xe7,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xe8[5] = {
    // #####
    // #∙##∙
    // #∙#∙∙
    // #∙∙∙∙
    // #∙∙#∙
    // #∙##∙
    // #####
    0x02, 0x56, 0xf6, 0xa4, 0x00
};
static const tImage Font_5x7_0xe8 = { image_data_Font_5x7_0xe8,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xe9[5] = {
    // ##∙∙#
    // #∙##∙
    // #∙#∙∙
    // #∙∙∙∙
    // #∙∙#∙
    // #∙##∙
    // #####
    0x32, 0x56, 0xf6, 0xa4, 0x00
};
static const tImage Font_5x7_0xe9 = { image_data_Font_5x7_0xe9,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xea[5] = {
    // #####
    // #∙##∙
    // #∙#∙#
    // #∙∙##
    // #∙#∙#
    // #∙##∙
    // #####
    0x02, 0x54, 0xc5, 0x24, 0x00
};
static const tImage Font_5x7_0xea = { image_data_Font_5x7_0xea,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xeb[5] = {
    // #####
    // ##∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ∙###∙
    // #####
    0x01, 0xd2, 0x94, 0xc4, 0x00
};
static const tImage Font_5x7_0xeb = { image_data_Font_5x7_0xeb,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xec[5] = {
    // #####
    // ∙###∙
    // ∙∙#∙∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙###∙
    // #####
    0x04, 0x77, 0x5a, 0xc4, 0x00
};
static const tImage Font_5x7_0xec = { image_data_Font_5x7_0xec,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xed[5] = {
    // #####
    // #∙##∙
    // #∙##∙
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #####
    0x02, 0x52, 0xf4, 0xa4, 0x00
};
static const tImage Font_5x7_0xed = { image_data_Font_5x7_0xed,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xee[5] = {
    // #####
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x01, 0x92, 0x94, 0x98, 0x00
};
static const tImage Font_5x7_0xee = { image_data_Font_5x7_0xee,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xef[5] = {
    // #####
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #####
    0x03, 0xd2, 0x94, 0xa4, 0x00
};
static const tImage Font_5x7_0xef = { image_data_Font_5x7_0xef,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xf0[5] = {
    // #####
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #∙###
    // #∙###
    0x03, 0x92, 0x97, 0x21, 0x00
};
static const tImage Font_5x7_0xf0 = { image_data_Font_5x7_0xf0,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xf1[5] = {
    // #####
    // ##∙∙#
    // #∙##∙
    // #∙###
    // #∙##∙
    // ##∙∙#
    // #####
    0x01, 0x92, 0x84, 0x98, 0x00
};
static const tImage Font_5x7_0xf1 = { image_data_Font_5x7_0xf1,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xf2[5] = {
    // #####
    // #∙∙∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0x03, 0x88, 0x42, 0x10, 0x00
};
static const tImage Font_5x7_0xf2 = { image_data_Font_5x7_0xf2,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xf3[5] = {
    // #####
    // #∙#∙#
    // #∙#∙#
    // #∙#∙#
    // ##∙∙#
    // ###∙#
    // #∙∙∙#
    0x02, 0x94, 0xa3, 0x09, 0xc0
};
static const tImage Font_5x7_0xf3 = { image_data_Font_5x7_0xf3,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xf4[5] = {
    // #####
    // ##∙##
    // ∙∙∙∙∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙∙∙∙∙
    // ##∙##
    0x01, 0x3f, 0x5a, 0xfc, 0x80
};
static const tImage Font_5x7_0xf4 = { image_data_Font_5x7_0xf4,
    5, 7};
#endif

#if (0x078 == 0x0)
static const uint8_t image_data_Font_5x7_0xf5[5] = {
    // #####
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #####
    0x02, 0x52, 0x64, 0xa4, 0x00
};
static const tImage Font_5x7_0xf5 = { image_data_Font_5x7_0xf5,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xf6[5] = {
    // #####
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙∙∙∙
    // ####∙
    0x02, 0x52, 0x94, 0xbc, 0x20
};
static const tImage Font_5x7_0xf6 = { image_data_Font_5x7_0xf6,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xf7[5] = {
    // #####
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // ####∙
    // ####∙
    // #####
    0x02, 0x52, 0x70, 0x84, 0x00
};
static const tImage Font_5x7_0xf7 = { image_data_Font_5x7_0xf7,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xf8[5] = {
    // #####
    // ∙###∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙∙∙∙∙
    // #####
    0x04, 0x6b, 0x5a, 0xfc, 0x00
};
static const tImage Font_5x7_0xf8 = { image_data_Font_5x7_0xf8,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xf9[5] = {
    // #####
    // ∙###∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙∙∙∙∙
    // ####∙
    0x04, 0x6b, 0x5a, 0xfc, 0x20
};
static const tImage Font_5x7_0xf9 = { image_data_Font_5x7_0xf9,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xfa[5] = {
    // #####
    // ∙∙###
    // #∙###
    // #∙∙∙#
    // #∙##∙
    // #∙∙∙#
    // #####
    0x06, 0x10, 0xe4, 0xb8, 0x00
};
static const tImage Font_5x7_0xfa = { image_data_Font_5x7_0xfa,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xfb[5] = {
    // #####
    // #∙##∙
    // #∙##∙
    // #∙∙#∙
    // #∙#∙∙
    // #∙∙#∙
    // #####
    0x02, 0x52, 0xd5, 0xb4, 0x00
};
static const tImage Font_5x7_0xfb = { image_data_Font_5x7_0xfb,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xfc[5] = {
    // #####
    // #∙###
    // #∙###
    // #∙∙∙#
    // #∙##∙
    // #∙∙∙#
    // #####
    0x02, 0x10, 0xe4, 0xb8, 0x00
};
static const tImage Font_5x7_0xfc = { image_data_Font_5x7_0xfc,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xfd[5] = {
    // #####
    // #∙∙∙#
    // ####∙
    // ##∙∙∙
    // ####∙
    // #∙∙∙#
    // #####
    0x03, 0x82, 0x70, 0xb8, 0x00
};
static const tImage Font_5x7_0xfd = { image_data_Font_5x7_0xfd,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xfe[5] = {
    // #####
    // ∙#∙∙∙
    // ∙#∙#∙
    // ∙#∙#∙
    // ∙∙∙#∙
    // ∙#∙∙∙
    // #####
    0x05, 0xeb, 0x5e, 0xdc, 0x00
};
static const tImage Font_5x7_0xfe = { image_data_Font_5x7_0xfe,
    5, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_5x7_0xff[5] = {
    // #####
    // ##∙∙∙
    // #∙##∙
    // ##∙∙∙
    // ##∙#∙
    // #∙##∙
    // #####
    0x01, 0xd2, 0x72, 0xa4, 0x00
};
static const tImage Font_5x7_0xff = { image_data_Font_5x7_0xff,
    5, 7};
#endif


static const tChar Font_5x7_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Font_5x7_0x20},
#else
  // character: ' ' == ''
  {0x20, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &Font_5x7_0x21},
#else
  // character: '!' == ''
  {0x21, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &Font_5x7_0x22},
#else
  // character: '"' == ''
  {0x22, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &Font_5x7_0x23},
#else
  // character: '#' == ''
  {0x23, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &Font_5x7_0x24},
#else
  // character: '$' == ''
  {0x24, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Font_5x7_0x25},
#else
  // character: '%' == ''
  {0x25, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &Font_5x7_0x26},
#else
  // character: '&' == ''
  {0x26, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &Font_5x7_0x27},
#else
  // character: ''' == ''
  {0x27, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &Font_5x7_0x28},
#else
  // character: '(' == ''
  {0x28, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &Font_5x7_0x29},
#else
  // character: ')' == ''
  {0x29, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &Font_5x7_0x2a},
#else
  // character: '*' == ''
  {0x2a, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &Font_5x7_0x2b},
#else
  // character: '+' == ''
  {0x2b, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Font_5x7_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Font_5x7_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Font_5x7_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &Font_5x7_0x2f},
#else
  // character: '/' == ''
  {0x2f, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font_5x7_0x30},
#else
  // character: '0' == ''
  {0x30, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font_5x7_0x31},
#else
  // character: '1' == ''
  {0x31, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font_5x7_0x32},
#else
  // character: '2' == ''
  {0x32, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font_5x7_0x33},
#else
  // character: '3' == ''
  {0x33, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font_5x7_0x34},
#else
  // character: '4' == ''
  {0x34, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font_5x7_0x35},
#else
  // character: '5' == ''
  {0x35, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font_5x7_0x36},
#else
  // character: '6' == ''
  {0x36, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font_5x7_0x37},
#else
  // character: '7' == ''
  {0x37, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font_5x7_0x38},
#else
  // character: '8' == ''
  {0x38, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font_5x7_0x39},
#else
  // character: '9' == ''
  {0x39, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Font_5x7_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &Font_5x7_0x3b},
#else
  // character: ';' == ''
  {0x3b, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &Font_5x7_0x3c},
#else
  // character: '<' == ''
  {0x3c, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &Font_5x7_0x3d},
#else
  // character: '=' == ''
  {0x3d, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &Font_5x7_0x3e},
#else
  // character: '>' == ''
  {0x3e, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &Font_5x7_0x3f},
#else
  // character: '?' == ''
  {0x3f, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &Font_5x7_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Font_5x7_0x41},
#else
  // character: 'A' == ''
  {0x41, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Font_5x7_0x42},
#else
  // character: 'B' == ''
  {0x42, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Font_5x7_0x43},
#else
  // character: 'C' == ''
  {0x43, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Font_5x7_0x44},
#else
  // character: 'D' == ''
  {0x44, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Font_5x7_0x45},
#else
  // character: 'E' == ''
  {0x45, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Font_5x7_0x46},
#else
  // character: 'F' == ''
  {0x46, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Font_5x7_0x47},
#else
  // character: 'G' == ''
  {0x47, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Font_5x7_0x48},
#else
  // character: 'H' == ''
  {0x48, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &Font_5x7_0x49},
#else
  // character: 'I' == ''
  {0x49, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Font_5x7_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Font_5x7_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Font_5x7_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Font_5x7_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Font_5x7_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &Font_5x7_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Font_5x7_0x50},
#else
  // character: 'P' == ''
  {0x50, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Font_5x7_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Font_5x7_0x52},
#else
  // character: 'R' == ''
  {0x52, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Font_5x7_0x53},
#else
  // character: 'S' == ''
  {0x53, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Font_5x7_0x54},
#else
  // character: 'T' == ''
  {0x54, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Font_5x7_0x55},
#else
  // character: 'U' == ''
  {0x55, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Font_5x7_0x56},
#else
  // character: 'V' == ''
  {0x56, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Font_5x7_0x57},
#else
  // character: 'W' == ''
  {0x57, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Font_5x7_0x58},
#else
  // character: 'X' == ''
  {0x58, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Font_5x7_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Font_5x7_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &Font_5x7_0x5b},
#else
  // character: '[' == ''
  {0x5b, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &Font_5x7_0x5c},
#else
  // character: '\' == ''
  {0x5c, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &Font_5x7_0x5d},
#else
  // character: ']' == ''
  {0x5d, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &Font_5x7_0x5e},
#else
  // character: '^' == ''
  {0x5e, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &Font_5x7_0x5f},
#else
  // character: '_' == ''
  {0x5f, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &Font_5x7_0x60},
#else
  // character: '`' == ''
  {0x60, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Font_5x7_0x61},
#else
  // character: 'a' == ''
  {0x61, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &Font_5x7_0x62},
#else
  // character: 'b' == ''
  {0x62, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Font_5x7_0x63},
#else
  // character: 'c' == ''
  {0x63, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &Font_5x7_0x64},
#else
  // character: 'd' == ''
  {0x64, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &Font_5x7_0x65},
#else
  // character: 'e' == ''
  {0x65, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &Font_5x7_0x66},
#else
  // character: 'f' == ''
  {0x66, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &Font_5x7_0x67},
#else
  // character: 'g' == ''
  {0x67, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Font_5x7_0x68},
#else
  // character: 'h' == ''
  {0x68, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &Font_5x7_0x69},
#else
  // character: 'i' == ''
  {0x69, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &Font_5x7_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &Font_5x7_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &Font_5x7_0x},
#endif

#if (0x029 == 0x0)
  // character: 'l'
  {0x6c, &Font_5x7_0x6c},
#else
  // character: 'l' == ')'
  {0x6c, &Font_5x7_0x29},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Font_5x7_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &Font_5x7_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &Font_5x7_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &Font_5x7_0x70},
#else
  // character: 'p' == ''
  {0x70, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &Font_5x7_0x71},
#else
  // character: 'q' == ''
  {0x71, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &Font_5x7_0x72},
#else
  // character: 'r' == ''
  {0x72, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &Font_5x7_0x73},
#else
  // character: 's' == ''
  {0x73, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &Font_5x7_0x74},
#else
  // character: 't' == ''
  {0x74, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &Font_5x7_0x75},
#else
  // character: 'u' == ''
  {0x75, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &Font_5x7_0x76},
#else
  // character: 'v' == ''
  {0x76, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &Font_5x7_0x77},
#else
  // character: 'w' == ''
  {0x77, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &Font_5x7_0x78},
#else
  // character: 'x' == ''
  {0x78, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &Font_5x7_0x79},
#else
  // character: 'y' == ''
  {0x79, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &Font_5x7_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &Font_5x7_0x7b},
#else
  // character: '{' == ''
  {0x7b, &Font_5x7_0x},
#endif

#if (0x029 == 0x0)
  // character: '|'
  {0x7c, &Font_5x7_0x7c},
#else
  // character: '|' == ')'
  {0x7c, &Font_5x7_0x29},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &Font_5x7_0x7d},
#else
  // character: '}' == ''
  {0x7d, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &Font_5x7_0x7e},
#else
  // character: '~' == ''
  {0x7e, &Font_5x7_0x},
#endif

#if (0x041 == 0x0)
  // character: 'А'
  {0xc0, &Font_5x7_0xc0},
#else
  // character: 'А' == 'A'
  {0xc0, &Font_5x7_0x41},
#endif

#if (0x0 == 0x0)
  // character: 'Б'
  {0xc1, &Font_5x7_0xc1},
#else
  // character: 'Б' == ''
  {0xc1, &Font_5x7_0x},
#endif

#if (0x042 == 0x0)
  // character: 'В'
  {0xc2, &Font_5x7_0xc2},
#else
  // character: 'В' == 'B'
  {0xc2, &Font_5x7_0x42},
#endif

#if (0x0 == 0x0)
  // character: 'Г'
  {0xc3, &Font_5x7_0xc3},
#else
  // character: 'Г' == ''
  {0xc3, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Д'
  {0xc4, &Font_5x7_0xc4},
#else
  // character: 'Д' == ''
  {0xc4, &Font_5x7_0x},
#endif

#if (0x045 == 0x0)
  // character: 'Е'
  {0xc5, &Font_5x7_0xc5},
#else
  // character: 'Е' == 'E'
  {0xc5, &Font_5x7_0x45},
#endif

#if (0x0 == 0x0)
  // character: 'Ж'
  {0xc6, &Font_5x7_0xc6},
#else
  // character: 'Ж' == ''
  {0xc6, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'З'
  {0xc7, &Font_5x7_0xc7},
#else
  // character: 'З' == ''
  {0xc7, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'И'
  {0xc8, &Font_5x7_0xc8},
#else
  // character: 'И' == ''
  {0xc8, &Font_5x7_0x},
#endif

#if (0x0c8 == 0x0)
  // character: 'Й'
  {0xc9, &Font_5x7_0xc9},
#else
  // character: 'Й' == 'И'
  {0xc9, &Font_5x7_0xc8},
#endif

#if (0x0 == 0x0)
  // character: 'К'
  {0xca, &Font_5x7_0xca},
#else
  // character: 'К' == ''
  {0xca, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Л'
  {0xcb, &Font_5x7_0xcb},
#else
  // character: 'Л' == ''
  {0xcb, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'М'
  {0xcc, &Font_5x7_0xcc},
#else
  // character: 'М' == ''
  {0xcc, &Font_5x7_0x},
#endif

#if (0x048 == 0x0)
  // character: 'Н'
  {0xcd, &Font_5x7_0xcd},
#else
  // character: 'Н' == 'H'
  {0xcd, &Font_5x7_0x48},
#endif

#if (0x04f == 0x0)
  // character: 'О'
  {0xce, &Font_5x7_0xce},
#else
  // character: 'О' == 'O'
  {0xce, &Font_5x7_0x4f},
#endif

#if (0x0 == 0x0)
  // character: 'П'
  {0xcf, &Font_5x7_0xcf},
#else
  // character: 'П' == ''
  {0xcf, &Font_5x7_0x},
#endif

#if (0x050 == 0x0)
  // character: 'Р'
  {0xd0, &Font_5x7_0xd0},
#else
  // character: 'Р' == 'P'
  {0xd0, &Font_5x7_0x50},
#endif

#if (0x043 == 0x0)
  // character: 'С'
  {0xd1, &Font_5x7_0xd1},
#else
  // character: 'С' == 'C'
  {0xd1, &Font_5x7_0x43},
#endif

#if (0x054 == 0x0)
  // character: 'Т'
  {0xd2, &Font_5x7_0xd2},
#else
  // character: 'Т' == 'T'
  {0xd2, &Font_5x7_0x54},
#endif

#if (0x0 == 0x0)
  // character: 'У'
  {0xd3, &Font_5x7_0xd3},
#else
  // character: 'У' == ''
  {0xd3, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ф'
  {0xd4, &Font_5x7_0xd4},
#else
  // character: 'Ф' == ''
  {0xd4, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Х'
  {0xd5, &Font_5x7_0xd5},
#else
  // character: 'Х' == ''
  {0xd5, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ц'
  {0xd6, &Font_5x7_0xd6},
#else
  // character: 'Ц' == ''
  {0xd6, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ч'
  {0xd7, &Font_5x7_0xd7},
#else
  // character: 'Ч' == ''
  {0xd7, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ш'
  {0xd8, &Font_5x7_0xd8},
#else
  // character: 'Ш' == ''
  {0xd8, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Щ'
  {0xd9, &Font_5x7_0xd9},
#else
  // character: 'Щ' == ''
  {0xd9, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ъ'
  {0xda, &Font_5x7_0xda},
#else
  // character: 'Ъ' == ''
  {0xda, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ы'
  {0xdb, &Font_5x7_0xdb},
#else
  // character: 'Ы' == ''
  {0xdb, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ь'
  {0xdc, &Font_5x7_0xdc},
#else
  // character: 'Ь' == ''
  {0xdc, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Э'
  {0xdd, &Font_5x7_0xdd},
#else
  // character: 'Э' == ''
  {0xdd, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ю'
  {0xde, &Font_5x7_0xde},
#else
  // character: 'Ю' == ''
  {0xde, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Я'
  {0xdf, &Font_5x7_0xdf},
#else
  // character: 'Я' == ''
  {0xdf, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'а'
  {0xe0, &Font_5x7_0xe0},
#else
  // character: 'а' == ''
  {0xe0, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'б'
  {0xe1, &Font_5x7_0xe1},
#else
  // character: 'б' == ''
  {0xe1, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'в'
  {0xe2, &Font_5x7_0xe2},
#else
  // character: 'в' == ''
  {0xe2, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'г'
  {0xe3, &Font_5x7_0xe3},
#else
  // character: 'г' == ''
  {0xe3, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'д'
  {0xe4, &Font_5x7_0xe4},
#else
  // character: 'д' == ''
  {0xe4, &Font_5x7_0x},
#endif

#if (0x065 == 0x0)
  // character: 'е'
  {0xe5, &Font_5x7_0xe5},
#else
  // character: 'е' == 'e'
  {0xe5, &Font_5x7_0x65},
#endif

#if (0x0 == 0x0)
  // character: 'ж'
  {0xe6, &Font_5x7_0xe6},
#else
  // character: 'ж' == ''
  {0xe6, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'з'
  {0xe7, &Font_5x7_0xe7},
#else
  // character: 'з' == ''
  {0xe7, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'и'
  {0xe8, &Font_5x7_0xe8},
#else
  // character: 'и' == ''
  {0xe8, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'й'
  {0xe9, &Font_5x7_0xe9},
#else
  // character: 'й' == ''
  {0xe9, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'к'
  {0xea, &Font_5x7_0xea},
#else
  // character: 'к' == ''
  {0xea, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'л'
  {0xeb, &Font_5x7_0xeb},
#else
  // character: 'л' == ''
  {0xeb, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'м'
  {0xec, &Font_5x7_0xec},
#else
  // character: 'м' == ''
  {0xec, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'н'
  {0xed, &Font_5x7_0xed},
#else
  // character: 'н' == ''
  {0xed, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'о'
  {0xee, &Font_5x7_0xee},
#else
  // character: 'о' == ''
  {0xee, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'п'
  {0xef, &Font_5x7_0xef},
#else
  // character: 'п' == ''
  {0xef, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'р'
  {0xf0, &Font_5x7_0xf0},
#else
  // character: 'р' == ''
  {0xf0, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'с'
  {0xf1, &Font_5x7_0xf1},
#else
  // character: 'с' == ''
  {0xf1, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'т'
  {0xf2, &Font_5x7_0xf2},
#else
  // character: 'т' == ''
  {0xf2, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'у'
  {0xf3, &Font_5x7_0xf3},
#else
  // character: 'у' == ''
  {0xf3, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ф'
  {0xf4, &Font_5x7_0xf4},
#else
  // character: 'ф' == ''
  {0xf4, &Font_5x7_0x},
#endif

#if (0x078 == 0x0)
  // character: 'х'
  {0xf5, &Font_5x7_0xf5},
#else
  // character: 'х' == 'x'
  {0xf5, &Font_5x7_0x78},
#endif

#if (0x0 == 0x0)
  // character: 'ц'
  {0xf6, &Font_5x7_0xf6},
#else
  // character: 'ц' == ''
  {0xf6, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ч'
  {0xf7, &Font_5x7_0xf7},
#else
  // character: 'ч' == ''
  {0xf7, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ш'
  {0xf8, &Font_5x7_0xf8},
#else
  // character: 'ш' == ''
  {0xf8, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'щ'
  {0xf9, &Font_5x7_0xf9},
#else
  // character: 'щ' == ''
  {0xf9, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ъ'
  {0xfa, &Font_5x7_0xfa},
#else
  // character: 'ъ' == ''
  {0xfa, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ы'
  {0xfb, &Font_5x7_0xfb},
#else
  // character: 'ы' == ''
  {0xfb, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ь'
  {0xfc, &Font_5x7_0xfc},
#else
  // character: 'ь' == ''
  {0xfc, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'э'
  {0xfd, &Font_5x7_0xfd},
#else
  // character: 'э' == ''
  {0xfd, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ю'
  {0xfe, &Font_5x7_0xfe},
#else
  // character: 'ю' == ''
  {0xfe, &Font_5x7_0x},
#endif

#if (0x0 == 0x0)
  // character: 'я'
  {0xff, &Font_5x7_0xff}
#else
  // character: 'я' == ''
  {0xff, &Font_5x7_0x}
#endif

};


const tFont Font_5x7 = { 159, Font_5x7_array };

