
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: C:/LW/bmp/lcd-image-converter/Font_7x10.xml
* name: Font_7x10
* family: Arial
* size: 10
* style: Обычный
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюя\x001e\x001f\x0018\x0019\x001a\x001b\x001c\x001d
* antialiasing: no
* type: monospaced
* encoding: CP1251
* unicode bom: no
*
* preset name: Монохромное
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>
#include "bmp.h"



#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x18[13] = {
    // ##∙∙∙∙∙∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙∙∙∙∙∙##
    // ##########
    // ##########
    // ##########
    0x3f, 0x08, 0x42, 0x10, 0x84, 0x21, 0x08, 0x43, 0xf0, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x18 = { image_data_Font_7x10_0x18,
    10, 10};
#endif

#if (0x018 == 0x0)
static const uint8_t image_data_Font_7x10_0x19[13] = {
    // ##∙∙∙∙∙∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙∙∙∙∙∙##
    // ##########
    // ##########
    // ##########
    0x3f, 0x08, 0x42, 0x10, 0x84, 0x21, 0x08, 0x43, 0xf0, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x19 = { image_data_Font_7x10_0x19,
    10, 10};
#endif

#if (0x018 == 0x0)
static const uint8_t image_data_Font_7x10_0x1a[13] = {
    // ##∙∙∙∙∙∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙####∙##
    // ##∙∙∙∙∙∙##
    // ##########
    // ##########
    // ##########
    0x3f, 0x08, 0x42, 0x10, 0x84, 0x21, 0x08, 0x43, 0xf0, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x1a = { image_data_Font_7x10_0x1a,
    10, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x1b[32] = {
    // #∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙#######
    // #∙##############∙∙∙∙∙∙∙∙#
    // #∙#∙#∙##∙∙∙#∙∙##∙∙#####∙#
    // #∙#∙#∙#∙####∙#∙#∙∙##∙##∙#
    // #∙#∙#∙##∙∙##∙∙##∙∙#####∙#
    // #∙#∙#∙####∙#∙#∙#∙∙##∙##∙#
    // #∙##∙∙#∙∙∙##∙∙##∙∙#####∙#
    // #∙##############∙∙∙∙∙∙∙∙#
    // #∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙#######
    // #########################
    0x7f, 0xff, 0xc0, 0x20, 0x00, 0x7f, 0x95, 0x3b, 0x30, 0x4a, 0xa1, 0x59, 0x25, 0x4c, 0xcc, 0x12, 0xa1, 0x56, 0x49, 0x37, 0x33, 0x04, 0x80, 0x01, 0xfe, 0x7f, 0xff, 0xc0, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x1b = { image_data_Font_7x10_0x1b,
    25, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x1c[34] = {
    // ###########################
    // #∙##∙##∙##∙##∙##∙##∙##∙##∙#
    // ##∙#∙#∙####∙#∙#∙####∙#∙#∙##
    // ###∙∙∙######∙∙∙######∙∙∙###
    // #∙∙∙∙∙∙∙##∙∙∙∙∙∙∙##∙∙∙∙∙∙∙#
    // ###∙∙∙######∙∙∙######∙∙∙###
    // ##∙#∙#∙####∙#∙#∙####∙#∙#∙##
    // #∙##∙##∙##∙##∙##∙##∙##∙##∙#
    // ###########################
    // ###########################
    0x00, 0x00, 0x00, 0x09, 0x24, 0x92, 0x48, 0xa8, 0x54, 0x2a, 0x0e, 0x07, 0x03, 0x87, 0xf3, 0xf9, 0xfc, 0x38, 0x1c, 0x0e, 0x0a, 0x85, 0x42, 0xa2, 0x49, 0x24, 0x92, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x1c = { image_data_Font_7x10_0x1c,
    27, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x1d[14] = {
    // ###∙∙∙∙∙###
    // ##∙##∙##∙##
    // #∙##∙∙∙##∙#
    // #∙#∙#∙#∙#∙#
    // #∙∙∙∙∙∙∙∙∙#
    // #∙#∙#∙#∙#∙#
    // #∙##∙∙∙##∙#
    // ##∙##∙##∙##
    // ###∙∙∙∙∙###
    // ###########
    0x1f, 0x04, 0x91, 0x39, 0x2a, 0xa7, 0xfc, 0xaa, 0x93, 0x91, 0x24, 0x1f, 0x00, 0x00
};
static const tImage Font_7x10_0x1d = { image_data_Font_7x10_0x1d,
    11, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x1e[9] = {
    // #######
    // ##∙∙###
    // ##∙∙###
    // #######
    // ##∙∙###
    // ##∙∙###
    // #######
    // ##∙∙###
    // ##∙∙###
    // #######
    0x00, 0x60, 0xc0, 0x03, 0x06, 0x00, 0x18, 0x30, 0x00
};
static const tImage Font_7x10_0x1e = { image_data_Font_7x10_0x1e,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x1f[9] = {
    // #######
    // #######
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙∙∙∙#
    // #∙∙∙∙∙#
    // #######
    // #######
    // #######
    0x00, 0x01, 0x83, 0x06, 0x0f, 0x9f, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x1f = { image_data_Font_7x10_0x1f,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x20[7] = {
    // #####
    // #####
    // #####
    // #####
    // #####
    // #####
    // #####
    // #####
    // #####
    // #####
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x20 = { image_data_Font_7x10_0x20,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x21[9] = {
    // #######
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // #######
    // ###∙∙##
    // ###∙∙##
    // #######
    0x00, 0x30, 0x60, 0xc1, 0x83, 0x00, 0x0c, 0x18, 0x00
};
static const tImage Font_7x10_0x21 = { image_data_Font_7x10_0x21,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x22[9] = {
    // #######
    // ##∙##∙#
    // ##∙##∙#
    // ##∙##∙#
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    0x00, 0x48, 0x91, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x22 = { image_data_Font_7x10_0x22,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x23[9] = {
    // #######
    // ##∙#∙##
    // ##∙#∙##
    // #∙∙∙∙∙#
    // ##∙#∙##
    // #∙∙∙∙∙#
    // ##∙#∙##
    // ##∙#∙##
    // #######
    // #######
    0x00, 0x50, 0xa3, 0xe2, 0x8f, 0x8a, 0x14, 0x00, 0x00
};
static const tImage Font_7x10_0x23 = { image_data_Font_7x10_0x23,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x24[9] = {
    // ###∙###
    // ##∙∙∙##
    // #∙#∙#∙#
    // #∙∙∙###
    // ###∙∙∙#
    // ###∙#∙#
    // #∙#∙#∙#
    // ##∙∙∙##
    // ###∙###
    // #######
    0x10, 0x71, 0x53, 0x81, 0xc2, 0x95, 0x1c, 0x10, 0x00
};
static const tImage Font_7x10_0x24 = { image_data_Font_7x10_0x24,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x25[9] = {
    // #######
    // #######
    // #∙###∙#
    // ∙#∙#∙##
    // ∙#∙#∙##
    // #∙#∙#∙#
    // ###∙∙#∙
    // ##∙#∙#∙
    // ##∙##∙#
    // #######
    0x00, 0x01, 0x15, 0x4a, 0x8a, 0x86, 0x95, 0x24, 0x00
};
static const tImage Font_7x10_0x25 = { image_data_Font_7x10_0x25,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x26[9] = {
    // #######
    // #######
    // ##∙∙∙##
    // #∙##∙##
    // ##∙∙###
    // #∙∙####
    // ∙##∙#∙∙
    // ∙###∙∙#
    // #∙∙∙#∙∙
    // #######
    0x00, 0x00, 0xe2, 0x43, 0x0c, 0x25, 0xc6, 0x76, 0x00
};
static const tImage Font_7x10_0x26 = { image_data_Font_7x10_0x26,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x27[9] = {
    // #######
    // ##∙####
    // ##∙####
    // ##∙####
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    0x00, 0x40, 0x81, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x27 = { image_data_Font_7x10_0x27,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x28[9] = {
    // ####∙##
    // ###∙###
    // ##∙####
    // ##∙####
    // ##∙####
    // ##∙####
    // ##∙####
    // ###∙###
    // ####∙##
    // #######
    0x08, 0x20, 0x81, 0x02, 0x04, 0x08, 0x08, 0x08, 0x00
};
static const tImage Font_7x10_0x28 = { image_data_Font_7x10_0x28,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x29[9] = {
    // ##∙####
    // ###∙###
    // ####∙##
    // ####∙##
    // ####∙##
    // ####∙##
    // ####∙##
    // ###∙###
    // ##∙####
    // #######
    0x20, 0x20, 0x20, 0x40, 0x81, 0x02, 0x08, 0x20, 0x00
};
static const tImage Font_7x10_0x29 = { image_data_Font_7x10_0x29,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x2a[9] = {
    // #######
    // ##∙#∙##
    // ###∙###
    // ##∙#∙##
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    0x00, 0x50, 0x41, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x2a = { image_data_Font_7x10_0x2a,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x2b[9] = {
    // #######
    // #######
    // ###∙###
    // ###∙###
    // #∙∙∙∙∙#
    // ###∙###
    // ###∙###
    // #######
    // #######
    // #######
    0x00, 0x00, 0x40, 0x87, 0xc2, 0x04, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x2b = { image_data_Font_7x10_0x2b,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x2c[9] = {
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    // ###∙∙##
    // ####∙##
    // ####∙##
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x08, 0x10
};
static const tImage Font_7x10_0x2c = { image_data_Font_7x10_0x2c,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x2d[9] = {
    // #######
    // #######
    // #######
    // #######
    // ##∙∙∙##
    // #######
    // #######
    // #######
    // #######
    // #######
    0x00, 0x00, 0x00, 0x03, 0x80, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x2d = { image_data_Font_7x10_0x2d,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x2e[9] = {
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    // ###∙∙##
    // ###∙∙##
    // #######
    // #######
    0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x0c, 0x00, 0x00
};
static const tImage Font_7x10_0x2e = { image_data_Font_7x10_0x2e,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x2f[9] = {
    // #######
    // ####∙##
    // ####∙##
    // ###∙###
    // ###∙###
    // ###∙###
    // ##∙####
    // ##∙####
    // #######
    // #######
    0x00, 0x10, 0x20, 0x81, 0x02, 0x08, 0x10, 0x00, 0x00
};
static const tImage Font_7x10_0x2f = { image_data_Font_7x10_0x2f,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x30[9] = {
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙#∙∙
    // #∙∙#∙∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xcd, 0x9b, 0xb6, 0xec, 0xd9, 0xb3, 0x3c, 0x00
};
static const tImage Font_7x10_0x30 = { image_data_Font_7x10_0x30,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x31[9] = {
    // ###∙∙##
    // ##∙∙∙##
    // #∙∙∙∙##
    // #∙#∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ##∙∙∙∙#
    // #######
    0x18, 0x71, 0xe2, 0xc1, 0x83, 0x06, 0x0c, 0x3c, 0x00
};
static const tImage Font_7x10_0x31 = { image_data_Font_7x10_0x31,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x32[9] = {
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙####∙
    // #####∙∙
    // ####∙∙#
    // ###∙∙##
    // ##∙∙###
    // #∙∙####
    // #∙∙∙∙∙∙
    // #######
    0x3c, 0xcd, 0x08, 0x30, 0xc3, 0x0c, 0x30, 0x7e, 0x00
};
static const tImage Font_7x10_0x32 = { image_data_Font_7x10_0x32,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x33[9] = {
    // ##∙∙∙∙#
    // #∙###∙∙
    // #####∙∙
    // ##∙∙∙∙#
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #∙###∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0x8c, 0x19, 0xe0, 0x60, 0xc1, 0xa3, 0x3c, 0x00
};
static const tImage Font_7x10_0x33 = { image_data_Font_7x10_0x33,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x34[9] = {
    // ####∙∙∙
    // ###∙∙∙∙
    // ##∙∙#∙∙
    // ##∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙∙∙∙
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #######
    0x0e, 0x3c, 0xd9, 0x36, 0x6f, 0xc1, 0x83, 0x06, 0x00
};
static const tImage Font_7x10_0x34 = { image_data_Font_7x10_0x34,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x35[9] = {
    // #∙∙∙∙∙∙
    // #∙∙####
    // #∙∙####
    // ##∙∙∙∙#
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #∙###∙∙
    // ##∙∙∙∙#
    // #######
    0x7e, 0xc1, 0x81, 0xe0, 0x60, 0xc1, 0xa3, 0x3c, 0x00
};
static const tImage Font_7x10_0x35 = { image_data_Font_7x10_0x35,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x36[9] = {
    // ##∙∙∙∙#
    // #∙∙###∙
    // #∙∙####
    // #∙∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xc5, 0x83, 0xe6, 0x6c, 0xd9, 0xb3, 0x3c, 0x00
};
static const tImage Font_7x10_0x36 = { image_data_Font_7x10_0x36,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x37[9] = {
    // #∙∙∙∙∙∙
    // #####∙∙
    // #####∙∙
    // ####∙∙#
    // ####∙∙#
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // #######
    0x7e, 0x0c, 0x18, 0x60, 0xc3, 0x06, 0x0c, 0x18, 0x00
};
static const tImage Font_7x10_0x37 = { image_data_Font_7x10_0x37,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x38[9] = {
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xcd, 0x99, 0xe6, 0x6c, 0xd9, 0xb3, 0x3c, 0x00
};
static const tImage Font_7x10_0x38 = { image_data_Font_7x10_0x38,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x39[9] = {
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙∙
    // #####∙∙
    // #####∙∙
    // #∙###∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xcd, 0x9b, 0x33, 0xe0, 0xc1, 0xa3, 0x3c, 0x00
};
static const tImage Font_7x10_0x39 = { image_data_Font_7x10_0x39,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x3a[9] = {
    // ###∙∙##
    // ###∙∙##
    // #######
    // #######
    // #######
    // ###∙∙##
    // ###∙∙##
    // #######
    // #######
    // #######
    0x18, 0x30, 0x00, 0x00, 0x03, 0x06, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x3a = { image_data_Font_7x10_0x3a,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x3b[9] = {
    // ###∙∙##
    // ###∙∙##
    // #######
    // #######
    // ###∙∙##
    // ###∙∙##
    // ####∙##
    // ####∙##
    // #######
    // #######
    0x18, 0x30, 0x00, 0x01, 0x83, 0x02, 0x04, 0x00, 0x00
};
static const tImage Font_7x10_0x3b = { image_data_Font_7x10_0x3b,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x3c[9] = {
    // #######
    // ####∙∙#
    // ###∙∙##
    // ##∙∙###
    // #∙∙####
    // ##∙∙###
    // ###∙∙##
    // ####∙∙#
    // #######
    // #######
    0x00, 0x18, 0x61, 0x86, 0x06, 0x06, 0x06, 0x00, 0x00
};
static const tImage Font_7x10_0x3c = { image_data_Font_7x10_0x3c,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x3d[9] = {
    // #######
    // #∙∙∙∙∙#
    // #∙∙∙∙∙#
    // #######
    // #∙∙∙∙∙#
    // #∙∙∙∙∙#
    // #######
    // #######
    // #######
    // #######
    0x00, 0xf9, 0xf0, 0x07, 0xcf, 0x80, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x3d = { image_data_Font_7x10_0x3d,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x3e[9] = {
    // #######
    // #∙∙####
    // ##∙∙###
    // ###∙∙##
    // ####∙∙#
    // ###∙∙##
    // ##∙∙###
    // #∙∙####
    // #######
    // #######
    0x00, 0xc0, 0xc0, 0xc0, 0xc3, 0x0c, 0x30, 0x00, 0x00
};
static const tImage Font_7x10_0x3e = { image_data_Font_7x10_0x3e,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x3f[9] = {
    // ##∙∙∙∙#
    // #∙####∙
    // #∙####∙
    // #####∙∙
    // ####∙∙#
    // ###∙∙##
    // #######
    // ###∙∙##
    // ###∙∙##
    // #######
    0x3c, 0x85, 0x08, 0x30, 0xc3, 0x00, 0x0c, 0x18, 0x00
};
static const tImage Font_7x10_0x3f = { image_data_Font_7x10_0x3f,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x40[9] = {
    // ##∙∙∙∙#
    // #∙####∙
    // ∙##∙##∙
    // ∙#∙#∙#∙
    // ∙#∙#∙#∙
    // ∙#∙#∙#∙
    // ∙##∙#∙#
    // #∙#####
    // ##∙∙∙∙∙
    // #######
    0x3c, 0x86, 0x4d, 0x5a, 0xb5, 0x65, 0x20, 0x3e, 0x00
};
static const tImage Font_7x10_0x40 = { image_data_Font_7x10_0x40,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x41[9] = {
    // ###∙∙##
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙∙∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x18, 0x79, 0x9b, 0x37, 0xec, 0xd9, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0x41 = { image_data_Font_7x10_0x41,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x42[9] = {
    // #∙∙∙∙∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙∙∙∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙∙∙∙#
    // #######
    0x7c, 0xc5, 0x8b, 0xe6, 0x2c, 0x58, 0xb1, 0x7c, 0x00
};
static const tImage Font_7x10_0x42 = { image_data_Font_7x10_0x42,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x43[9] = {
    // ##∙∙∙∙#
    // #∙∙###∙
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙###∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xc5, 0x83, 0x06, 0x0c, 0x18, 0x31, 0x3c, 0x00
};
static const tImage Font_7x10_0x43 = { image_data_Font_7x10_0x43,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x44[9] = {
    // #∙∙∙∙##
    // #∙∙##∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙##∙#
    // #∙∙∙∙##
    // #######
    0x78, 0xc9, 0x8b, 0x16, 0x2c, 0x58, 0xb2, 0x78, 0x00
};
static const tImage Font_7x10_0x44 = { image_data_Font_7x10_0x44,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x45[9] = {
    // #∙∙∙∙∙∙
    // #∙∙####
    // #∙∙####
    // #∙∙∙∙∙#
    // #∙∙∙∙∙#
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙∙∙∙∙
    // #######
    0x7e, 0xc1, 0x83, 0xe7, 0xcc, 0x18, 0x30, 0x7e, 0x00
};
static const tImage Font_7x10_0x45 = { image_data_Font_7x10_0x45,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x46[9] = {
    // #∙∙∙∙∙∙
    // #∙∙####
    // #∙∙####
    // #∙∙∙∙∙#
    // #∙∙∙∙∙#
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #######
    0x7e, 0xc1, 0x83, 0xe7, 0xcc, 0x18, 0x30, 0x60, 0x00
};
static const tImage Font_7x10_0x46 = { image_data_Font_7x10_0x46,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x47[9] = {
    // ##∙∙∙∙#
    // #∙∙###∙
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙##∙∙
    // #∙∙###∙
    // #∙∙###∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xc5, 0x83, 0x06, 0x0c, 0xd8, 0xb1, 0x3c, 0x00
};
static const tImage Font_7x10_0x47 = { image_data_Font_7x10_0x47,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x48[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙∙∙∙
    // #∙∙∙∙∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x66, 0xcd, 0x9b, 0xf7, 0xec, 0xd9, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0x48 = { image_data_Font_7x10_0x48,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x49[9] = {
    // ##∙∙∙∙#
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ##∙∙∙∙#
    // #######
    0x3c, 0x30, 0x60, 0xc1, 0x83, 0x06, 0x0c, 0x3c, 0x00
};
static const tImage Font_7x10_0x49 = { image_data_Font_7x10_0x49,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x4a[9] = {
    // ####∙∙∙
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #∙###∙∙
    // #∙###∙∙
    // ##∙∙∙∙#
    // #######
    0x0e, 0x0c, 0x18, 0x30, 0x60, 0xd1, 0xa3, 0x3c, 0x00
};
static const tImage Font_7x10_0x4a = { image_data_Font_7x10_0x4a,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x4b[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙#∙∙#
    // #∙∙∙###
    // #∙∙#∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x66, 0xcd, 0x9b, 0x67, 0x0d, 0x99, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0x4b = { image_data_Font_7x10_0x4b,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x4c[9] = {
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙###∙
    // #∙∙∙∙∙∙
    // #######
    0x60, 0xc1, 0x83, 0x06, 0x0c, 0x18, 0x31, 0x7e, 0x00
};
static const tImage Font_7x10_0x4c = { image_data_Font_7x10_0x4c,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x4d[13] = {
    // #∙∙#####∙∙
    // #∙∙∙###∙∙∙
    // #∙∙#∙#∙#∙∙
    // #∙∙#∙#∙#∙∙
    // #∙∙#∙#∙#∙∙
    // #∙∙##∙##∙∙
    // #∙∙#####∙∙
    // #∙∙#####∙∙
    // #∙∙#####∙∙
    // ##########
    0x60, 0xdc, 0x76, 0xad, 0xab, 0x6a, 0xd9, 0x36, 0x0d, 0x83, 0x60, 0xc0, 0x00
};
static const tImage Font_7x10_0x4d = { image_data_Font_7x10_0x4d,
    10, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x4e[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙#∙∙
    // #∙∙∙#∙∙
    // #∙∙#∙∙∙
    // #∙∙#∙∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x66, 0xcd, 0xdb, 0xb6, 0xed, 0xd9, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0x4e = { image_data_Font_7x10_0x4e,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x4f[9] = {
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xcd, 0x9b, 0x36, 0x6c, 0xd9, 0xb3, 0x3c, 0x00
};
static const tImage Font_7x10_0x4f = { image_data_Font_7x10_0x4f,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x50[9] = {
    // #∙∙∙∙∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙∙∙∙#
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #######
    0x7c, 0xc5, 0x8b, 0x17, 0xcc, 0x18, 0x30, 0x60, 0x00
};
static const tImage Font_7x10_0x50 = { image_data_Font_7x10_0x50,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x51[9] = {
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // #####∙∙
    0x3c, 0xcd, 0x9b, 0x36, 0x6c, 0xd9, 0xb3, 0x3c, 0x0c
};
static const tImage Font_7x10_0x51 = { image_data_Font_7x10_0x51,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x52[9] = {
    // #∙∙∙∙∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙∙∙∙#
    // #∙∙##∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #######
    0x7c, 0xc5, 0x8b, 0x17, 0xcc, 0x98, 0xb1, 0x62, 0x00
};
static const tImage Font_7x10_0x52 = { image_data_Font_7x10_0x52,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x53[9] = {
    // ##∙∙∙∙#
    // #∙∙###∙
    // #∙∙####
    // ##∙∙∙∙#
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #∙###∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xc5, 0x81, 0xe0, 0x60, 0xc1, 0xa3, 0x3c, 0x00
};
static const tImage Font_7x10_0x53 = { image_data_Font_7x10_0x53,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x54[9] = {
    // #∙∙∙∙∙∙
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // #######
    0x7e, 0x30, 0x60, 0xc1, 0x83, 0x06, 0x0c, 0x18, 0x00
};
static const tImage Font_7x10_0x54 = { image_data_Font_7x10_0x54,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x55[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // #######
    0x66, 0xcd, 0x9b, 0x36, 0x6c, 0xd9, 0xb3, 0x3c, 0x00
};
static const tImage Font_7x10_0x55 = { image_data_Font_7x10_0x55,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x56[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙##∙#
    // ##∙##∙#
    // ##∙##∙#
    // ###∙∙##
    // #######
    0x66, 0xcd, 0x9b, 0x36, 0x64, 0x89, 0x12, 0x18, 0x00
};
static const tImage Font_7x10_0x56 = { image_data_Font_7x10_0x56,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x57[10] = {
    // #∙∙###∙∙
    // #∙∙###∙∙
    // #∙∙###∙∙
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // ##∙∙∙∙∙#
    // ###∙#∙##
    // ########
    0x63, 0x63, 0x63, 0x6b, 0x6b, 0x6b, 0x6b, 0x3e, 0x14, 0x00
};
static const tImage Font_7x10_0x57 = { image_data_Font_7x10_0x57,
    8, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x58[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // ###∙∙##
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x66, 0xcd, 0x99, 0xe1, 0x87, 0x99, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0x58 = { image_data_Font_7x10_0x58,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x59[9] = {
    // #∙####∙
    // #∙####∙
    // ##∙##∙#
    // ##∙∙∙∙#
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // #######
    0x42, 0x84, 0x91, 0xe1, 0x83, 0x06, 0x0c, 0x18, 0x00
};
static const tImage Font_7x10_0x59 = { image_data_Font_7x10_0x59,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x5a[9] = {
    // #∙∙∙∙∙∙
    // #∙###∙∙
    // #####∙∙
    // ####∙∙#
    // ###∙∙##
    // ##∙∙###
    // #∙∙####
    // #∙∙###∙
    // #∙∙∙∙∙∙
    // #######
    0x7e, 0x8c, 0x18, 0x61, 0x86, 0x18, 0x31, 0x7e, 0x00
};
static const tImage Font_7x10_0x5a = { image_data_Font_7x10_0x5a,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x5b[9] = {
    // ##∙∙∙∙#
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙∙∙#
    // #######
    0x3c, 0x60, 0xc1, 0x83, 0x06, 0x0c, 0x18, 0x3c, 0x00
};
static const tImage Font_7x10_0x5b = { image_data_Font_7x10_0x5b,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x5c[9] = {
    // ##∙####
    // ##∙∙###
    // ###∙###
    // ###∙###
    // ###∙∙##
    // ####∙##
    // ####∙##
    // ####∙∙#
    // #####∙#
    // #######
    0x20, 0x60, 0x40, 0x81, 0x81, 0x02, 0x06, 0x04, 0x00
};
static const tImage Font_7x10_0x5c = { image_data_Font_7x10_0x5c,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x5d[9] = {
    // ##∙∙∙∙#
    // ####∙∙#
    // ####∙∙#
    // ####∙∙#
    // ####∙∙#
    // ####∙∙#
    // ####∙∙#
    // ####∙∙#
    // ##∙∙∙∙#
    // #######
    0x3c, 0x18, 0x30, 0x60, 0xc1, 0x83, 0x06, 0x3c, 0x00
};
static const tImage Font_7x10_0x5d = { image_data_Font_7x10_0x5d,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x5e[9] = {
    // ###∙###
    // ##∙∙∙##
    // #∙∙#∙∙#
    // ∙∙###∙∙
    // ∙#####∙
    // #######
    // #######
    // #######
    // #######
    // #######
    0x10, 0x71, 0xb6, 0x38, 0x20, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x5e = { image_data_Font_7x10_0x5e,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x5f[9] = {
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    // #∙∙∙∙∙∙
    // #######
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7e, 0x00
};
static const tImage Font_7x10_0x5f = { image_data_Font_7x10_0x5f,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x60[9] = {
    // ####∙##
    // ####∙∙#
    // #####∙#
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    // #######
    0x08, 0x18, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x60 = { image_data_Font_7x10_0x60,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x61[8] = {
    // ######
    // ######
    // ##∙∙∙#
    // #∙###∙
    // #####∙
    // ##∙∙∙∙
    // #∙###∙
    // #∙###∙
    // ##∙∙∙#
    // ######
    0x00, 0x03, 0x91, 0x04, 0xf4, 0x51, 0x38, 0x00
};
static const tImage Font_7x10_0x61 = { image_data_Font_7x10_0x61,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x62[8] = {
    // ######
    // #∙####
    // #∙####
    // #∙####
    // #∙∙∙∙#
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // ##∙∙∙#
    // ######
    0x01, 0x04, 0x10, 0x79, 0x14, 0x51, 0x38, 0x00
};
static const tImage Font_7x10_0x62 = { image_data_Font_7x10_0x62,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x63[8] = {
    // ######
    // ######
    // ##∙∙∙#
    // #∙###∙
    // #∙####
    // #∙####
    // #∙####
    // #∙###∙
    // ##∙∙∙#
    // ######
    0x00, 0x03, 0x91, 0x41, 0x04, 0x11, 0x38, 0x00
};
static const tImage Font_7x10_0x63 = { image_data_Font_7x10_0x63,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x64[8] = {
    // ######
    // #####∙
    // #####∙
    // #####∙
    // ##∙∙∙∙
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // ##∙∙∙∙
    // ######
    0x00, 0x10, 0x41, 0x3d, 0x14, 0x51, 0x3c, 0x00
};
static const tImage Font_7x10_0x64 = { image_data_Font_7x10_0x64,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x65[8] = {
    // ######
    // ######
    // ##∙∙∙#
    // #∙###∙
    // #∙###∙
    // #∙∙∙∙∙
    // #∙####
    // #∙###∙
    // ##∙∙∙#
    // ######
    0x00, 0x03, 0x91, 0x45, 0xf4, 0x11, 0x38, 0x00
};
static const tImage Font_7x10_0x65 = { image_data_Font_7x10_0x65,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x66[7] = {
    // #####
    // ###∙#
    // ##∙##
    // #∙∙∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0x00, 0x88, 0xe2, 0x10, 0x84, 0x20, 0x00
};
static const tImage Font_7x10_0x66 = { image_data_Font_7x10_0x66,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x67[8] = {
    // ######
    // ######
    // ##∙∙∙#
    // #∙###∙
    // #∙###∙
    // ##∙∙∙∙
    // #####∙
    // #####∙
    // #∙###∙
    // ##∙∙∙#
    0x00, 0x03, 0x91, 0x44, 0xf0, 0x41, 0x44, 0xe0
};
static const tImage Font_7x10_0x67 = { image_data_Font_7x10_0x67,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x68[8] = {
    // #∙####
    // #∙####
    // #∙####
    // #∙####
    // #∙∙∙∙#
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // ######
    0x41, 0x04, 0x10, 0x79, 0x14, 0x51, 0x44, 0x00
};
static const tImage Font_7x10_0x68 = { image_data_Font_7x10_0x68,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x69[4] = {
    // ###
    // #∙#
    // ###
    // #∙#
    // #∙#
    // #∙#
    // #∙#
    // #∙#
    // #∙#
    // ###
    0x08, 0x24, 0x92, 0x40
};
static const tImage Font_7x10_0x69 = { image_data_Font_7x10_0x69,
    3, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x6a[5] = {
    // ####
    // ##∙#
    // ####
    // ##∙#
    // ##∙#
    // ##∙#
    // ##∙#
    // ##∙#
    // ##∙#
    // #∙##
    0x02, 0x02, 0x22, 0x22, 0x24
};
static const tImage Font_7x10_0x6a = { image_data_Font_7x10_0x6a,
    4, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x6b[7] = {
    // #####
    // #####
    // #∙##∙
    // #∙#∙#
    // #∙∙##
    // #∙∙##
    // #∙#∙#
    // #∙##∙
    // #∙##∙
    // #####
    0x00, 0x12, 0xa6, 0x31, 0x49, 0x48, 0x00
};
static const tImage Font_7x10_0x6b = { image_data_Font_7x10_0x6b,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x6c[4] = {
    // #∙#
    // #∙#
    // #∙#
    // #∙#
    // #∙#
    // #∙#
    // #∙#
    // #∙#
    // #∙#
    // ###
    0x49, 0x24, 0x92, 0x40
};
static const tImage Font_7x10_0x6c = { image_data_Font_7x10_0x6c,
    3, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x6d[10] = {
    // ########
    // ########
    // #∙∙∙∙∙∙#
    // #∙##∙##∙
    // #∙##∙##∙
    // #∙##∙##∙
    // #∙##∙##∙
    // #∙##∙##∙
    // #∙##∙##∙
    // ########
    0x00, 0x00, 0x7e, 0x49, 0x49, 0x49, 0x49, 0x49, 0x49, 0x00
};
static const tImage Font_7x10_0x6d = { image_data_Font_7x10_0x6d,
    8, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x6e[8] = {
    // ######
    // ######
    // #∙∙∙∙#
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // ######
    0x00, 0x07, 0x91, 0x45, 0x14, 0x51, 0x44, 0x00
};
static const tImage Font_7x10_0x6e = { image_data_Font_7x10_0x6e,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x6f[8] = {
    // ######
    // ######
    // ##∙∙∙#
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // #∙###∙
    // ##∙∙∙#
    // ######
    0x00, 0x03, 0x91, 0x45, 0x14, 0x51, 0x38, 0x00
};
static const tImage Font_7x10_0x6f = { image_data_Font_7x10_0x6f,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x70[7] = {
    // #####
    // #####
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #∙###
    // #∙###
    // #∙###
    0x00, 0x1c, 0x94, 0xa5, 0xc8, 0x42, 0x00
};
static const tImage Font_7x10_0x70 = { image_data_Font_7x10_0x70,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x71[7] = {
    // #####
    // #####
    // ##∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // ####∙
    // ####∙
    // ####∙
    0x00, 0x0e, 0x94, 0xa4, 0xe1, 0x08, 0x40
};
static const tImage Font_7x10_0x71 = { image_data_Font_7x10_0x71,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x72[7] = {
    // #####
    // #####
    // #∙#∙∙
    // #∙∙##
    // #∙###
    // #∙###
    // #∙###
    // #∙###
    // #∙###
    // #####
    0x00, 0x16, 0xc4, 0x21, 0x08, 0x40, 0x00
};
static const tImage Font_7x10_0x72 = { image_data_Font_7x10_0x72,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x73[7] = {
    // #####
    // #####
    // ##∙∙∙
    // #∙###
    // #∙###
    // ##∙∙#
    // ####∙
    // ####∙
    // #∙∙∙#
    // #####
    0x00, 0x0e, 0x84, 0x18, 0x21, 0x70, 0x00
};
static const tImage Font_7x10_0x73 = { image_data_Font_7x10_0x73,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x74[7] = {
    // #####
    // ##∙##
    // ##∙##
    // #∙∙∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙∙#
    // #####
    0x01, 0x08, 0xe2, 0x10, 0x84, 0x30, 0x00
};
static const tImage Font_7x10_0x74 = { image_data_Font_7x10_0x74,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x75[7] = {
    // #####
    // #####
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // #####
    0x00, 0x12, 0x94, 0xa5, 0x29, 0x38, 0x00
};
static const tImage Font_7x10_0x75 = { image_data_Font_7x10_0x75,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x76[8] = {
    // ######
    // ######
    // #∙###∙
    // #∙###∙
    // #∙∙#∙∙
    // ##∙#∙#
    // ##∙#∙#
    // ###∙##
    // ###∙##
    // ######
    0x00, 0x04, 0x51, 0x6c, 0xa2, 0x84, 0x10, 0x00
};
static const tImage Font_7x10_0x76 = { image_data_Font_7x10_0x76,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x77[10] = {
    // ########
    // ########
    // #∙#####∙
    // #∙##∙##∙
    // #∙##∙##∙
    // #∙##∙##∙
    // #∙∙#∙#∙∙
    // ##∙∙∙∙∙#
    // ###∙#∙##
    // ########
    0x00, 0x00, 0x41, 0x49, 0x49, 0x49, 0x6b, 0x3e, 0x14, 0x00
};
static const tImage Font_7x10_0x77 = { image_data_Font_7x10_0x77,
    8, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x78[8] = {
    // ######
    // ######
    // #∙###∙
    // #∙###∙
    // ##∙#∙#
    // ###∙##
    // ##∙#∙#
    // #∙###∙
    // #∙###∙
    // ######
    0x00, 0x04, 0x51, 0x28, 0x42, 0x91, 0x44, 0x00
};
static const tImage Font_7x10_0x78 = { image_data_Font_7x10_0x78,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x79[8] = {
    // ######
    // ######
    // #∙###∙
    // #∙###∙
    // ##∙#∙#
    // ##∙#∙#
    // ###∙##
    // ###∙##
    // #∙∙###
    // ######
    0x00, 0x04, 0x51, 0x28, 0xa1, 0x04, 0x60, 0x00
};
static const tImage Font_7x10_0x79 = { image_data_Font_7x10_0x79,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x7a[8] = {
    // ######
    // ######
    // #∙∙∙∙∙
    // #####∙
    // ####∙#
    // ###∙##
    // ##∙###
    // #∙####
    // #∙∙∙∙∙
    // ######
    0x00, 0x07, 0xc1, 0x08, 0x42, 0x10, 0x7c, 0x00
};
static const tImage Font_7x10_0x7a = { image_data_Font_7x10_0x7a,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x7b[7] = {
    // ##∙∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // #∙###
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙∙#
    // #####
    0x31, 0x08, 0x44, 0x10, 0x84, 0x30, 0x00
};
static const tImage Font_7x10_0x7b = { image_data_Font_7x10_0x7b,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x7c[7] = {
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // #####
    0x21, 0x08, 0x42, 0x10, 0x84, 0x20, 0x00
};
static const tImage Font_7x10_0x7c = { image_data_Font_7x10_0x7c,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x7d[7] = {
    // #∙∙##
    // ##∙##
    // ##∙##
    // ##∙##
    // ###∙#
    // ##∙##
    // ##∙##
    // ##∙##
    // #∙∙##
    // #####
    0x61, 0x08, 0x41, 0x10, 0x84, 0x60, 0x00
};
static const tImage Font_7x10_0x7d = { image_data_Font_7x10_0x7d,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0x7e[8] = {
    // ######
    // ######
    // ######
    // ######
    // #∙∙∙#∙
    // #∙#∙∙∙
    // ######
    // ######
    // ######
    // ######
    0x00, 0x00, 0x00, 0x75, 0x70, 0x00, 0x00, 0x00
};
static const tImage Font_7x10_0x7e = { image_data_Font_7x10_0x7e,
    6, 10};
#endif

#if (0x041 == 0x0)
static const uint8_t image_data_Font_7x10_0xc0[9] = {
    // ###∙∙##
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙∙∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x18, 0x79, 0x9b, 0x37, 0xec, 0xd9, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0xc0 = { image_data_Font_7x10_0xc0,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xc1[9] = {
    // #∙∙∙∙∙∙
    // #∙∙####
    // #∙∙####
    // #∙∙∙∙∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙∙∙∙#
    // #######
    0x7e, 0xc1, 0x83, 0xe6, 0x2c, 0x58, 0xb1, 0x7c, 0x00
};
static const tImage Font_7x10_0xc1 = { image_data_Font_7x10_0xc1,
    7, 10};
#endif

#if (0x042 == 0x0)
static const uint8_t image_data_Font_7x10_0xc2[9] = {
    // #∙∙∙∙∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙∙∙∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙∙∙∙#
    // #######
    0x7c, 0xc5, 0x8b, 0xe6, 0x2c, 0x58, 0xb1, 0x7c, 0x00
};
static const tImage Font_7x10_0xc2 = { image_data_Font_7x10_0xc2,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xc3[9] = {
    // ##∙∙∙∙∙
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // ##∙∙###
    // #######
    0x3e, 0x60, 0xc1, 0x83, 0x06, 0x0c, 0x18, 0x30, 0x00
};
static const tImage Font_7x10_0xc3 = { image_data_Font_7x10_0xc3,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xc4[9] = {
    // ####∙∙∙
    // ###∙#∙∙
    // ###∙#∙∙
    // ###∙#∙∙
    // ###∙#∙∙
    // ###∙#∙∙
    // ##∙##∙∙
    // ##∙##∙∙
    // #∙∙∙∙∙∙
    // #∙####∙
    0x0e, 0x2c, 0x58, 0xb1, 0x62, 0xc9, 0x93, 0x7e, 0x84
};
static const tImage Font_7x10_0xc4 = { image_data_Font_7x10_0xc4,
    7, 10};
#endif

#if (0x045 == 0x0)
static const uint8_t image_data_Font_7x10_0xc5[9] = {
    // #∙∙∙∙∙∙
    // #∙∙####
    // #∙∙####
    // #∙∙∙∙∙#
    // #∙∙∙∙∙#
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙∙∙∙∙
    // #######
    0x7e, 0xc1, 0x83, 0xe7, 0xcc, 0x18, 0x30, 0x7e, 0x00
};
static const tImage Font_7x10_0xc5 = { image_data_Font_7x10_0xc5,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xc6[10] = {
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // ##∙#∙#∙#
    // ###∙∙∙##
    // ####∙###
    // ###∙∙∙##
    // ##∙#∙#∙#
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // ########
    0x6b, 0x6b, 0x2a, 0x1c, 0x08, 0x1c, 0x2a, 0x6b, 0x6b, 0x00
};
static const tImage Font_7x10_0xc6 = { image_data_Font_7x10_0xc6,
    8, 10};
#endif

#if (0x033 == 0x0)
static const uint8_t image_data_Font_7x10_0xc7[9] = {
    // ##∙∙∙∙#
    // #∙###∙∙
    // #####∙∙
    // ##∙∙∙∙#
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #∙###∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0x8c, 0x19, 0xe0, 0x60, 0xc1, 0xa3, 0x3c, 0x00
};
static const tImage Font_7x10_0xc7 = { image_data_Font_7x10_0xc7,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xc8[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙#∙∙∙
    // #∙∙#∙∙∙
    // #∙∙∙∙∙∙
    // #∙∙∙#∙∙
    // #∙∙∙#∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x66, 0xcd, 0xbb, 0x77, 0xee, 0xdd, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0xc8 = { image_data_Font_7x10_0xc8,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xc9[9] = {
    // ###∙∙##
    // #∙∙##∙∙
    // #∙∙#∙∙∙
    // #∙∙#∙∙∙
    // #∙∙∙∙∙∙
    // #∙∙∙#∙∙
    // #∙∙∙#∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x18, 0xcd, 0xbb, 0x77, 0xee, 0xdd, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0xc9 = { image_data_Font_7x10_0xc9,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xca[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙#∙∙#
    // #∙∙∙∙##
    // #∙∙#∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x66, 0xcd, 0x9b, 0x67, 0x8d, 0x99, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0xca = { image_data_Font_7x10_0xca,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xcb[9] = {
    // ##∙∙∙∙∙
    // #∙∙∙∙∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ∙∙∙##∙∙
    // #######
    0x3e, 0xfd, 0x9b, 0x36, 0x6c, 0xd9, 0xb3, 0xe6, 0x00
};
static const tImage Font_7x10_0xcb = { image_data_Font_7x10_0xcb,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xcc[13] = {
    // #∙∙#####∙∙
    // #∙∙∙###∙∙∙
    // #∙∙∙###∙∙∙
    // #∙∙#∙#∙#∙∙
    // #∙∙#∙#∙#∙∙
    // #∙∙##∙##∙∙
    // #∙∙##∙##∙∙
    // #∙∙#####∙∙
    // #∙∙#####∙∙
    // ##########
    0x60, 0xdc, 0x77, 0x1d, 0xab, 0x6a, 0xd9, 0x36, 0x4d, 0x83, 0x60, 0xc0, 0x00
};
static const tImage Font_7x10_0xcc = { image_data_Font_7x10_0xcc,
    10, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xcd[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙∙∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x66, 0xcd, 0x9b, 0xf6, 0x6c, 0xd9, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0xcd = { image_data_Font_7x10_0xcd,
    7, 10};
#endif

#if (0x04f == 0x0)
static const uint8_t image_data_Font_7x10_0xce[9] = {
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xcd, 0x9b, 0x36, 0x6c, 0xd9, 0xb3, 0x3c, 0x00
};
static const tImage Font_7x10_0xce = { image_data_Font_7x10_0xce,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xcf[9] = {
    // #∙∙∙∙∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x7e, 0xcd, 0x9b, 0x36, 0x6c, 0xd9, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0xcf = { image_data_Font_7x10_0xcf,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xd0[9] = {
    // #∙∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙∙∙#
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #######
    0x7c, 0xcd, 0x9b, 0x37, 0xcc, 0x18, 0x30, 0x60, 0x00
};
static const tImage Font_7x10_0xd0 = { image_data_Font_7x10_0xd0,
    7, 10};
#endif

#if (0x043 == 0x0)
static const uint8_t image_data_Font_7x10_0xd1[9] = {
    // ##∙∙∙∙#
    // #∙∙###∙
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙###∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0xc5, 0x83, 0x06, 0x0c, 0x18, 0x31, 0x3c, 0x00
};
static const tImage Font_7x10_0xd1 = { image_data_Font_7x10_0xd1,
    7, 10};
#endif

#if (0x054 == 0x0)
static const uint8_t image_data_Font_7x10_0xd2[9] = {
    // #∙∙∙∙∙∙
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // ###∙∙##
    // #######
    0x7e, 0x30, 0x60, 0xc1, 0x83, 0x06, 0x0c, 0x18, 0x00
};
static const tImage Font_7x10_0xd2 = { image_data_Font_7x10_0xd2,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xd3[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙∙
    // #####∙∙
    // #####∙∙
    // ##∙∙∙∙#
    // #######
    0x66, 0xcd, 0x9b, 0x36, 0x67, 0xc1, 0x83, 0x3c, 0x00
};
static const tImage Font_7x10_0xd3 = { image_data_Font_7x10_0xd3,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xd4[9] = {
    // ###∙∙##
    // ##∙∙∙∙#
    // #∙#∙∙#∙
    // #∙#∙∙#∙
    // #∙#∙∙#∙
    // #∙#∙∙#∙
    // #∙#∙∙#∙
    // ##∙∙∙∙#
    // ###∙∙##
    // #######
    0x18, 0x79, 0x6a, 0xd5, 0xab, 0x56, 0x9e, 0x18, 0x00
};
static const tImage Font_7x10_0xd4 = { image_data_Font_7x10_0xd4,
    7, 10};
#endif

#if (0x058 == 0x0)
static const uint8_t image_data_Font_7x10_0xd5[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙#
    // ###∙∙##
    // ##∙∙∙∙#
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #######
    0x66, 0xcd, 0x99, 0xe1, 0x87, 0x99, 0xb3, 0x66, 0x00
};
static const tImage Font_7x10_0xd5 = { image_data_Font_7x10_0xd5,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xd6[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙∙∙∙
    // #####∙∙
    0x66, 0xcd, 0x9b, 0x36, 0x6c, 0xd9, 0xb3, 0x7e, 0x0c
};
static const tImage Font_7x10_0xd6 = { image_data_Font_7x10_0xd6,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xd7[9] = {
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // ##∙∙∙∙∙
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #######
    0x66, 0xcd, 0x9b, 0x33, 0xe0, 0xc1, 0x83, 0x06, 0x00
};
static const tImage Font_7x10_0xd7 = { image_data_Font_7x10_0xd7,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xd8[10] = {
    // #∙∙###∙∙
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // #∙∙#∙#∙∙
    // #∙∙∙∙∙∙∙
    // ########
    0x63, 0x6b, 0x6b, 0x6b, 0x6b, 0x6b, 0x6b, 0x6b, 0x7f, 0x00
};
static const tImage Font_7x10_0xd8 = { image_data_Font_7x10_0xd8,
    8, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xd9[12] = {
    // #∙∙###∙∙#
    // #∙∙#∙#∙∙#
    // #∙∙#∙#∙∙#
    // #∙∙#∙#∙∙#
    // #∙∙#∙#∙∙#
    // #∙∙#∙#∙∙#
    // #∙∙#∙#∙∙#
    // #∙∙#∙#∙∙#
    // #∙∙∙∙∙∙∙#
    // #######∙∙
    0x63, 0x35, 0x9a, 0xcd, 0x66, 0xb3, 0x59, 0xac, 0xd6, 0x7f, 0x00, 0xc0
};
static const tImage Font_7x10_0xd9 = { image_data_Font_7x10_0xd9,
    9, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xda[9] = {
    // ∙∙∙####
    // ∙∙∙####
    // #∙∙####
    // #∙∙∙∙∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // ##∙∙∙∙#
    // #######
    0xe1, 0xc1, 0x83, 0xe6, 0x2c, 0x58, 0xb1, 0x3c, 0x00
};
static const tImage Font_7x10_0xda = { image_data_Font_7x10_0xda,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xdb[9] = {
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙∙∙#∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙##∙∙
    // #∙∙∙∙#∙
    // #######
    0x62, 0xc5, 0x8b, 0x17, 0xac, 0xd9, 0xb3, 0x7a, 0x00
};
static const tImage Font_7x10_0xdb = { image_data_Font_7x10_0xdb,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xdc[9] = {
    // #∙∙####
    // #∙∙####
    // #∙∙####
    // #∙∙∙∙∙#
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // #∙∙###∙
    // ##∙∙∙∙#
    // #######
    0x60, 0xc1, 0x83, 0xe6, 0x2c, 0x58, 0xb1, 0x3c, 0x00
};
static const tImage Font_7x10_0xdc = { image_data_Font_7x10_0xdc,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xdd[9] = {
    // ##∙∙∙∙#
    // #∙###∙∙
    // #####∙∙
    // ###∙∙∙∙
    // #####∙∙
    // #####∙∙
    // #####∙∙
    // #∙###∙∙
    // ##∙∙∙∙#
    // #######
    0x3c, 0x8c, 0x18, 0xf0, 0x60, 0xc1, 0xa3, 0x3c, 0x00
};
static const tImage Font_7x10_0xdd = { image_data_Font_7x10_0xdd,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xde[12] = {
    // #∙∙##∙∙∙#
    // #∙∙#∙∙##∙
    // #∙∙#∙∙##∙
    // #∙∙#∙∙##∙
    // #∙∙∙∙∙##∙
    // #∙∙#∙∙##∙
    // #∙∙#∙∙##∙
    // #∙∙#∙∙##∙
    // #∙∙##∙∙∙#
    // #########
    0x67, 0x36, 0x5b, 0x2d, 0x97, 0xcb, 0x65, 0xb2, 0xd9, 0x67, 0x00, 0x00
};
static const tImage Font_7x10_0xde = { image_data_Font_7x10_0xde,
    9, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xdf[9] = {
    // ##∙∙∙∙∙
    // #∙###∙∙
    // #∙###∙∙
    // #∙###∙∙
    // ##∙∙∙∙∙
    // #∙###∙∙
    // #∙###∙∙
    // #∙###∙∙
    // #∙###∙∙
    // #######
    0x3e, 0x8d, 0x1a, 0x33, 0xe8, 0xd1, 0xa3, 0x46, 0x00
};
static const tImage Font_7x10_0xdf = { image_data_Font_7x10_0xdf,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe0[7] = {
    // #####
    // #####
    // #####
    // ##∙∙∙
    // ####∙
    // ##∙∙∙
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x00, 0x00, 0x70, 0x9d, 0x29, 0x30, 0x00
};
static const tImage Font_7x10_0xe0 = { image_data_Font_7x10_0xe0,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe1[7] = {
    // #####
    // #####
    // ##∙∙∙
    // #∙###
    // #∙###
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x00, 0x0e, 0x84, 0x3d, 0x29, 0x30, 0x00
};
static const tImage Font_7x10_0xe1 = { image_data_Font_7x10_0xe1,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe2[7] = {
    // #####
    // #####
    // #####
    // #∙∙∙#
    // #∙##∙
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #####
    0x00, 0x00, 0xe4, 0xb9, 0x29, 0x70, 0x00
};
static const tImage Font_7x10_0xe2 = { image_data_Font_7x10_0xe2,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe3[5] = {
    // ####
    // ####
    // ####
    // #∙∙∙
    // #∙##
    // #∙##
    // #∙##
    // #∙##
    // #∙##
    // ####
    0x00, 0x07, 0x44, 0x44, 0x40
};
static const tImage Font_7x10_0xe3 = { image_data_Font_7x10_0xe3,
    4, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe4[8] = {
    // ######
    // ######
    // ######
    // ######
    // ##∙∙∙#
    // ##∙#∙#
    // ##∙#∙#
    // #∙##∙#
    // #∙∙∙∙∙
    // #∙###∙
    0x00, 0x00, 0x00, 0x38, 0xa2, 0x92, 0x7d, 0x10
};
static const tImage Font_7x10_0xe4 = { image_data_Font_7x10_0xe4,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe5[7] = {
    // #####
    // #####
    // #####
    // ##∙∙#
    // #∙##∙
    // #∙∙∙#
    // #∙###
    // #∙###
    // ##∙∙∙
    // #####
    0x00, 0x00, 0x64, 0xb9, 0x08, 0x38, 0x00
};
static const tImage Font_7x10_0xe5 = { image_data_Font_7x10_0xe5,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe6[8] = {
    // ######
    // ######
    // ######
    // #∙#∙#∙
    // ##∙∙∙#
    // ###∙##
    // ##∙∙∙#
    // #∙#∙#∙
    // #∙#∙#∙
    // ######
    0x00, 0x00, 0x15, 0x38, 0x43, 0x95, 0x54, 0x00
};
static const tImage Font_7x10_0xe6 = { image_data_Font_7x10_0xe6,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe7[7] = {
    // #####
    // #####
    // #####
    // ##∙∙#
    // #∙##∙
    // ###∙#
    // ####∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x00, 0x00, 0x64, 0x88, 0x29, 0x30, 0x00
};
static const tImage Font_7x10_0xe7 = { image_data_Font_7x10_0xe7,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe8[7] = {
    // #####
    // #####
    // #####
    // #∙##∙
    // #∙#∙∙
    // #∙#∙∙
    // #∙∙#∙
    // #∙∙#∙
    // #∙##∙
    // #####
    0x00, 0x00, 0x95, 0xad, 0xad, 0x48, 0x00
};
static const tImage Font_7x10_0xe8 = { image_data_Font_7x10_0xe8,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xe9[7] = {
    // #####
    // ##∙∙#
    // #####
    // #∙##∙
    // #∙#∙∙
    // #∙#∙∙
    // #∙∙#∙
    // #∙∙#∙
    // #∙##∙
    // #####
    0x01, 0x80, 0x95, 0xad, 0xad, 0x48, 0x00
};
static const tImage Font_7x10_0xe9 = { image_data_Font_7x10_0xe9,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xea[7] = {
    // #####
    // #####
    // #####
    // #∙##∙
    // #∙#∙#
    // #∙∙##
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #####
    0x00, 0x00, 0x95, 0x31, 0xc9, 0x48, 0x00
};
static const tImage Font_7x10_0xea = { image_data_Font_7x10_0xea,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xeb[8] = {
    // ######
    // ######
    // ######
    // ###∙∙∙
    // ##∙##∙
    // ##∙##∙
    // ##∙##∙
    // ##∙##∙
    // #∙###∙
    // ######
    0x00, 0x00, 0x07, 0x24, 0x92, 0x49, 0x44, 0x00
};
static const tImage Font_7x10_0xeb = { image_data_Font_7x10_0xeb,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xec[8] = {
    // ######
    // ######
    // ######
    // #∙###∙
    // #∙∙#∙∙
    // #∙#∙#∙
    // #∙#∙#∙
    // #∙###∙
    // #∙###∙
    // ######
    0x00, 0x00, 0x11, 0x6d, 0x55, 0x51, 0x44, 0x00
};
static const tImage Font_7x10_0xec = { image_data_Font_7x10_0xec,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xed[7] = {
    // #####
    // #####
    // #####
    // #∙##∙
    // #∙##∙
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #####
    0x00, 0x00, 0x94, 0xbd, 0x29, 0x48, 0x00
};
static const tImage Font_7x10_0xed = { image_data_Font_7x10_0xed,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xee[7] = {
    // #####
    // #####
    // #####
    // ##∙∙#
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x00, 0x00, 0x64, 0xa5, 0x29, 0x30, 0x00
};
static const tImage Font_7x10_0xee = { image_data_Font_7x10_0xee,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xef[7] = {
    // #####
    // #####
    // #####
    // #∙∙∙∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #####
    0x00, 0x00, 0xf4, 0xa5, 0x29, 0x48, 0x00
};
static const tImage Font_7x10_0xef = { image_data_Font_7x10_0xef,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf0[7] = {
    // #####
    // #####
    // #####
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #∙###
    // #∙###
    0x00, 0x00, 0xe4, 0xa5, 0x2e, 0x42, 0x00
};
static const tImage Font_7x10_0xf0 = { image_data_Font_7x10_0xf0,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf1[7] = {
    // #####
    // #####
    // #####
    // ##∙∙#
    // #∙##∙
    // #∙###
    // #∙###
    // #∙##∙
    // ##∙∙#
    // #####
    0x00, 0x00, 0x64, 0xa1, 0x09, 0x30, 0x00
};
static const tImage Font_7x10_0xf1 = { image_data_Font_7x10_0xf1,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf2[8] = {
    // ######
    // ######
    // ######
    // #∙∙∙∙∙
    // ###∙##
    // ###∙##
    // ###∙##
    // ###∙##
    // ###∙##
    // ######
    0x00, 0x00, 0x1f, 0x10, 0x41, 0x04, 0x10, 0x00
};
static const tImage Font_7x10_0xf2 = { image_data_Font_7x10_0xf2,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf3[7] = {
    // #####
    // #####
    // #####
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // ####∙
    // #∙∙∙#
    0x00, 0x00, 0x94, 0xa5, 0x27, 0x0b, 0x80
};
static const tImage Font_7x10_0xf3 = { image_data_Font_7x10_0xf3,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf4[8] = {
    // ######
    // ######
    // ###∙##
    // ##∙∙∙#
    // #∙#∙#∙
    // #∙#∙#∙
    // #∙#∙#∙
    // ##∙∙∙#
    // ###∙##
    // ######
    0x00, 0x01, 0x0e, 0x55, 0x55, 0x4e, 0x10, 0x00
};
static const tImage Font_7x10_0xf4 = { image_data_Font_7x10_0xf4,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf5[8] = {
    // ######
    // ######
    // ######
    // #∙###∙
    // ##∙#∙#
    // ###∙##
    // ##∙#∙#
    // #∙###∙
    // #∙###∙
    // ######
    0x00, 0x00, 0x11, 0x28, 0x42, 0x91, 0x44, 0x00
};
static const tImage Font_7x10_0xf5 = { image_data_Font_7x10_0xf5,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf6[8] = {
    // ######
    // ######
    // ######
    // #∙##∙#
    // #∙##∙#
    // #∙##∙#
    // #∙##∙#
    // #∙##∙#
    // #∙∙∙∙∙
    // #####∙
    0x00, 0x00, 0x12, 0x49, 0x24, 0x92, 0x7c, 0x10
};
static const tImage Font_7x10_0xf6 = { image_data_Font_7x10_0xf6,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf7[7] = {
    // #####
    // #####
    // #####
    // #∙##∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // ####∙
    // ####∙
    // #####
    0x00, 0x00, 0x94, 0xa4, 0xe1, 0x08, 0x00
};
static const tImage Font_7x10_0xf7 = { image_data_Font_7x10_0xf7,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf8[8] = {
    // ######
    // ######
    // ######
    // #∙###∙
    // #∙#∙#∙
    // #∙#∙#∙
    // #∙#∙#∙
    // #∙#∙#∙
    // #∙∙∙∙∙
    // ######
    0x00, 0x00, 0x11, 0x55, 0x55, 0x55, 0x7c, 0x00
};
static const tImage Font_7x10_0xf8 = { image_data_Font_7x10_0xf8,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xf9[9] = {
    // #######
    // #######
    // #######
    // #∙###∙#
    // #∙#∙#∙#
    // #∙#∙#∙#
    // #∙#∙#∙#
    // #∙#∙#∙#
    // #∙∙∙∙∙∙
    // ######∙
    0x00, 0x00, 0x02, 0x25, 0x4a, 0x95, 0x2a, 0x7e, 0x04
};
static const tImage Font_7x10_0xf9 = { image_data_Font_7x10_0xf9,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xfa[8] = {
    // ######
    // ######
    // ######
    // #∙∙###
    // ##∙###
    // ##∙∙∙#
    // ##∙##∙
    // ##∙##∙
    // ##∙∙∙#
    // ######
    0x00, 0x00, 0x18, 0x20, 0xe2, 0x49, 0x38, 0x00
};
static const tImage Font_7x10_0xfa = { image_data_Font_7x10_0xfa,
    6, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xfb[9] = {
    // #######
    // #######
    // #######
    // #∙####∙
    // #∙####∙
    // #∙∙∙##∙
    // #∙##∙#∙
    // #∙##∙#∙
    // #∙∙∙##∙
    // #######
    0x00, 0x00, 0x02, 0x14, 0x2e, 0x52, 0xa5, 0x72, 0x00
};
static const tImage Font_7x10_0xfb = { image_data_Font_7x10_0xfb,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xfc[7] = {
    // #####
    // #####
    // #####
    // #∙###
    // #∙###
    // #∙∙∙#
    // #∙##∙
    // #∙##∙
    // #∙∙∙#
    // #####
    0x00, 0x00, 0x84, 0x39, 0x29, 0x70, 0x00
};
static const tImage Font_7x10_0xfc = { image_data_Font_7x10_0xfc,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xfd[7] = {
    // #####
    // #####
    // #####
    // ##∙∙#
    // #∙##∙
    // ###∙∙
    // ####∙
    // #∙##∙
    // ##∙∙#
    // #####
    0x00, 0x00, 0x64, 0x8c, 0x29, 0x30, 0x00
};
static const tImage Font_7x10_0xfd = { image_data_Font_7x10_0xfd,
    5, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xfe[9] = {
    // #######
    // #######
    // #######
    // #∙##∙∙#
    // #∙#∙##∙
    // #∙#∙##∙
    // #∙∙∙##∙
    // #∙#∙##∙
    // #∙##∙∙#
    // #######
    0x00, 0x00, 0x02, 0x65, 0x2a, 0x5c, 0xa9, 0x4c, 0x00
};
static const tImage Font_7x10_0xfe = { image_data_Font_7x10_0xfe,
    7, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_7x10_0xff[7] = {
    // #####
    // #####
    // #####
    // ##∙∙∙
    // #∙##∙
    // #∙##∙
    // ##∙∙∙
    // #∙##∙
    // #∙##∙
    // #####
    0x00, 0x00, 0x74, 0xa4, 0xe9, 0x48, 0x00
};
static const tImage Font_7x10_0xff = { image_data_Font_7x10_0xff,
    5, 10};
#endif


static const tChar Font_7x10_array[] = {

#if (0x0 == 0x0)
  // character: '\x0018'
  {0x18, &Font_7x10_0x18},
#else
  // character: '\x0018' == ''
  {0x18, &Font_7x10_0x},
#endif

#if (0x018 == 0x0)
  // character: '\x0019'
  {0x19, &Font_7x10_0x19},
#else
  // character: '\x0019' == '\x0018'
  {0x19, &Font_7x10_0x18},
#endif

#if (0x018 == 0x0)
  // character: '\x001a'
  {0x1a, &Font_7x10_0x1a},
#else
  // character: '\x001a' == '\x0018'
  {0x1a, &Font_7x10_0x18},
#endif

#if (0x0 == 0x0)
  // character: '\x001b'
  {0x1b, &Font_7x10_0x1b},
#else
  // character: '\x001b' == ''
  {0x1b, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x001c'
  {0x1c, &Font_7x10_0x1c},
#else
  // character: '\x001c' == ''
  {0x1c, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x001d'
  {0x1d, &Font_7x10_0x1d},
#else
  // character: '\x001d' == ''
  {0x1d, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x001e'
  {0x1e, &Font_7x10_0x1e},
#else
  // character: '\x001e' == ''
  {0x1e, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x001f'
  {0x1f, &Font_7x10_0x1f},
#else
  // character: '\x001f' == ''
  {0x1f, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Font_7x10_0x20},
#else
  // character: ' ' == ''
  {0x20, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &Font_7x10_0x21},
#else
  // character: '!' == ''
  {0x21, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &Font_7x10_0x22},
#else
  // character: '"' == ''
  {0x22, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &Font_7x10_0x23},
#else
  // character: '#' == ''
  {0x23, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &Font_7x10_0x24},
#else
  // character: '$' == ''
  {0x24, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Font_7x10_0x25},
#else
  // character: '%' == ''
  {0x25, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &Font_7x10_0x26},
#else
  // character: '&' == ''
  {0x26, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &Font_7x10_0x27},
#else
  // character: ''' == ''
  {0x27, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &Font_7x10_0x28},
#else
  // character: '(' == ''
  {0x28, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &Font_7x10_0x29},
#else
  // character: ')' == ''
  {0x29, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &Font_7x10_0x2a},
#else
  // character: '*' == ''
  {0x2a, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &Font_7x10_0x2b},
#else
  // character: '+' == ''
  {0x2b, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Font_7x10_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Font_7x10_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Font_7x10_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &Font_7x10_0x2f},
#else
  // character: '/' == ''
  {0x2f, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font_7x10_0x30},
#else
  // character: '0' == ''
  {0x30, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font_7x10_0x31},
#else
  // character: '1' == ''
  {0x31, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font_7x10_0x32},
#else
  // character: '2' == ''
  {0x32, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font_7x10_0x33},
#else
  // character: '3' == ''
  {0x33, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font_7x10_0x34},
#else
  // character: '4' == ''
  {0x34, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font_7x10_0x35},
#else
  // character: '5' == ''
  {0x35, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font_7x10_0x36},
#else
  // character: '6' == ''
  {0x36, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font_7x10_0x37},
#else
  // character: '7' == ''
  {0x37, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font_7x10_0x38},
#else
  // character: '8' == ''
  {0x38, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font_7x10_0x39},
#else
  // character: '9' == ''
  {0x39, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Font_7x10_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &Font_7x10_0x3b},
#else
  // character: ';' == ''
  {0x3b, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &Font_7x10_0x3c},
#else
  // character: '<' == ''
  {0x3c, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &Font_7x10_0x3d},
#else
  // character: '=' == ''
  {0x3d, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &Font_7x10_0x3e},
#else
  // character: '>' == ''
  {0x3e, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &Font_7x10_0x3f},
#else
  // character: '?' == ''
  {0x3f, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &Font_7x10_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Font_7x10_0x41},
#else
  // character: 'A' == ''
  {0x41, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Font_7x10_0x42},
#else
  // character: 'B' == ''
  {0x42, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Font_7x10_0x43},
#else
  // character: 'C' == ''
  {0x43, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Font_7x10_0x44},
#else
  // character: 'D' == ''
  {0x44, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Font_7x10_0x45},
#else
  // character: 'E' == ''
  {0x45, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Font_7x10_0x46},
#else
  // character: 'F' == ''
  {0x46, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Font_7x10_0x47},
#else
  // character: 'G' == ''
  {0x47, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Font_7x10_0x48},
#else
  // character: 'H' == ''
  {0x48, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &Font_7x10_0x49},
#else
  // character: 'I' == ''
  {0x49, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Font_7x10_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Font_7x10_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Font_7x10_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Font_7x10_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Font_7x10_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &Font_7x10_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Font_7x10_0x50},
#else
  // character: 'P' == ''
  {0x50, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Font_7x10_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Font_7x10_0x52},
#else
  // character: 'R' == ''
  {0x52, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Font_7x10_0x53},
#else
  // character: 'S' == ''
  {0x53, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Font_7x10_0x54},
#else
  // character: 'T' == ''
  {0x54, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Font_7x10_0x55},
#else
  // character: 'U' == ''
  {0x55, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Font_7x10_0x56},
#else
  // character: 'V' == ''
  {0x56, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Font_7x10_0x57},
#else
  // character: 'W' == ''
  {0x57, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Font_7x10_0x58},
#else
  // character: 'X' == ''
  {0x58, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Font_7x10_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Font_7x10_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &Font_7x10_0x5b},
#else
  // character: '[' == ''
  {0x5b, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &Font_7x10_0x5c},
#else
  // character: '\' == ''
  {0x5c, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &Font_7x10_0x5d},
#else
  // character: ']' == ''
  {0x5d, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &Font_7x10_0x5e},
#else
  // character: '^' == ''
  {0x5e, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &Font_7x10_0x5f},
#else
  // character: '_' == ''
  {0x5f, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &Font_7x10_0x60},
#else
  // character: '`' == ''
  {0x60, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Font_7x10_0x61},
#else
  // character: 'a' == ''
  {0x61, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &Font_7x10_0x62},
#else
  // character: 'b' == ''
  {0x62, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Font_7x10_0x63},
#else
  // character: 'c' == ''
  {0x63, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &Font_7x10_0x64},
#else
  // character: 'd' == ''
  {0x64, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &Font_7x10_0x65},
#else
  // character: 'e' == ''
  {0x65, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &Font_7x10_0x66},
#else
  // character: 'f' == ''
  {0x66, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &Font_7x10_0x67},
#else
  // character: 'g' == ''
  {0x67, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Font_7x10_0x68},
#else
  // character: 'h' == ''
  {0x68, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &Font_7x10_0x69},
#else
  // character: 'i' == ''
  {0x69, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &Font_7x10_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &Font_7x10_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'l'
  {0x6c, &Font_7x10_0x6c},
#else
  // character: 'l' == ''
  {0x6c, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Font_7x10_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &Font_7x10_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &Font_7x10_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &Font_7x10_0x70},
#else
  // character: 'p' == ''
  {0x70, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &Font_7x10_0x71},
#else
  // character: 'q' == ''
  {0x71, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &Font_7x10_0x72},
#else
  // character: 'r' == ''
  {0x72, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &Font_7x10_0x73},
#else
  // character: 's' == ''
  {0x73, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &Font_7x10_0x74},
#else
  // character: 't' == ''
  {0x74, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &Font_7x10_0x75},
#else
  // character: 'u' == ''
  {0x75, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &Font_7x10_0x76},
#else
  // character: 'v' == ''
  {0x76, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &Font_7x10_0x77},
#else
  // character: 'w' == ''
  {0x77, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &Font_7x10_0x78},
#else
  // character: 'x' == ''
  {0x78, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &Font_7x10_0x79},
#else
  // character: 'y' == ''
  {0x79, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &Font_7x10_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &Font_7x10_0x7b},
#else
  // character: '{' == ''
  {0x7b, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &Font_7x10_0x7c},
#else
  // character: '|' == ''
  {0x7c, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &Font_7x10_0x7d},
#else
  // character: '}' == ''
  {0x7d, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &Font_7x10_0x7e},
#else
  // character: '~' == ''
  {0x7e, &Font_7x10_0x},
#endif

#if (0x041 == 0x0)
  // character: 'А'
  {0xc0, &Font_7x10_0xc0},
#else
  // character: 'А' == 'A'
  {0xc0, &Font_7x10_0x41},
#endif

#if (0x0 == 0x0)
  // character: 'Б'
  {0xc1, &Font_7x10_0xc1},
#else
  // character: 'Б' == ''
  {0xc1, &Font_7x10_0x},
#endif

#if (0x042 == 0x0)
  // character: 'В'
  {0xc2, &Font_7x10_0xc2},
#else
  // character: 'В' == 'B'
  {0xc2, &Font_7x10_0x42},
#endif

#if (0x0 == 0x0)
  // character: 'Г'
  {0xc3, &Font_7x10_0xc3},
#else
  // character: 'Г' == ''
  {0xc3, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Д'
  {0xc4, &Font_7x10_0xc4},
#else
  // character: 'Д' == ''
  {0xc4, &Font_7x10_0x},
#endif

#if (0x045 == 0x0)
  // character: 'Е'
  {0xc5, &Font_7x10_0xc5},
#else
  // character: 'Е' == 'E'
  {0xc5, &Font_7x10_0x45},
#endif

#if (0x0 == 0x0)
  // character: 'Ж'
  {0xc6, &Font_7x10_0xc6},
#else
  // character: 'Ж' == ''
  {0xc6, &Font_7x10_0x},
#endif

#if (0x033 == 0x0)
  // character: 'З'
  {0xc7, &Font_7x10_0xc7},
#else
  // character: 'З' == '3'
  {0xc7, &Font_7x10_0x33},
#endif

#if (0x0 == 0x0)
  // character: 'И'
  {0xc8, &Font_7x10_0xc8},
#else
  // character: 'И' == ''
  {0xc8, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Й'
  {0xc9, &Font_7x10_0xc9},
#else
  // character: 'Й' == ''
  {0xc9, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'К'
  {0xca, &Font_7x10_0xca},
#else
  // character: 'К' == ''
  {0xca, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Л'
  {0xcb, &Font_7x10_0xcb},
#else
  // character: 'Л' == ''
  {0xcb, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'М'
  {0xcc, &Font_7x10_0xcc},
#else
  // character: 'М' == ''
  {0xcc, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Н'
  {0xcd, &Font_7x10_0xcd},
#else
  // character: 'Н' == ''
  {0xcd, &Font_7x10_0x},
#endif

#if (0x04f == 0x0)
  // character: 'О'
  {0xce, &Font_7x10_0xce},
#else
  // character: 'О' == 'O'
  {0xce, &Font_7x10_0x4f},
#endif

#if (0x0 == 0x0)
  // character: 'П'
  {0xcf, &Font_7x10_0xcf},
#else
  // character: 'П' == ''
  {0xcf, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Р'
  {0xd0, &Font_7x10_0xd0},
#else
  // character: 'Р' == ''
  {0xd0, &Font_7x10_0x},
#endif

#if (0x043 == 0x0)
  // character: 'С'
  {0xd1, &Font_7x10_0xd1},
#else
  // character: 'С' == 'C'
  {0xd1, &Font_7x10_0x43},
#endif

#if (0x054 == 0x0)
  // character: 'Т'
  {0xd2, &Font_7x10_0xd2},
#else
  // character: 'Т' == 'T'
  {0xd2, &Font_7x10_0x54},
#endif

#if (0x0 == 0x0)
  // character: 'У'
  {0xd3, &Font_7x10_0xd3},
#else
  // character: 'У' == ''
  {0xd3, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ф'
  {0xd4, &Font_7x10_0xd4},
#else
  // character: 'Ф' == ''
  {0xd4, &Font_7x10_0x},
#endif

#if (0x058 == 0x0)
  // character: 'Х'
  {0xd5, &Font_7x10_0xd5},
#else
  // character: 'Х' == 'X'
  {0xd5, &Font_7x10_0x58},
#endif

#if (0x0 == 0x0)
  // character: 'Ц'
  {0xd6, &Font_7x10_0xd6},
#else
  // character: 'Ц' == ''
  {0xd6, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ч'
  {0xd7, &Font_7x10_0xd7},
#else
  // character: 'Ч' == ''
  {0xd7, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ш'
  {0xd8, &Font_7x10_0xd8},
#else
  // character: 'Ш' == ''
  {0xd8, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Щ'
  {0xd9, &Font_7x10_0xd9},
#else
  // character: 'Щ' == ''
  {0xd9, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ъ'
  {0xda, &Font_7x10_0xda},
#else
  // character: 'Ъ' == ''
  {0xda, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ы'
  {0xdb, &Font_7x10_0xdb},
#else
  // character: 'Ы' == ''
  {0xdb, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ь'
  {0xdc, &Font_7x10_0xdc},
#else
  // character: 'Ь' == ''
  {0xdc, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Э'
  {0xdd, &Font_7x10_0xdd},
#else
  // character: 'Э' == ''
  {0xdd, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ю'
  {0xde, &Font_7x10_0xde},
#else
  // character: 'Ю' == ''
  {0xde, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Я'
  {0xdf, &Font_7x10_0xdf},
#else
  // character: 'Я' == ''
  {0xdf, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'а'
  {0xe0, &Font_7x10_0xe0},
#else
  // character: 'а' == ''
  {0xe0, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'б'
  {0xe1, &Font_7x10_0xe1},
#else
  // character: 'б' == ''
  {0xe1, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'в'
  {0xe2, &Font_7x10_0xe2},
#else
  // character: 'в' == ''
  {0xe2, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'г'
  {0xe3, &Font_7x10_0xe3},
#else
  // character: 'г' == ''
  {0xe3, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'д'
  {0xe4, &Font_7x10_0xe4},
#else
  // character: 'д' == ''
  {0xe4, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'е'
  {0xe5, &Font_7x10_0xe5},
#else
  // character: 'е' == ''
  {0xe5, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ж'
  {0xe6, &Font_7x10_0xe6},
#else
  // character: 'ж' == ''
  {0xe6, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'з'
  {0xe7, &Font_7x10_0xe7},
#else
  // character: 'з' == ''
  {0xe7, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'и'
  {0xe8, &Font_7x10_0xe8},
#else
  // character: 'и' == ''
  {0xe8, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'й'
  {0xe9, &Font_7x10_0xe9},
#else
  // character: 'й' == ''
  {0xe9, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'к'
  {0xea, &Font_7x10_0xea},
#else
  // character: 'к' == ''
  {0xea, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'л'
  {0xeb, &Font_7x10_0xeb},
#else
  // character: 'л' == ''
  {0xeb, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'м'
  {0xec, &Font_7x10_0xec},
#else
  // character: 'м' == ''
  {0xec, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'н'
  {0xed, &Font_7x10_0xed},
#else
  // character: 'н' == ''
  {0xed, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'о'
  {0xee, &Font_7x10_0xee},
#else
  // character: 'о' == ''
  {0xee, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'п'
  {0xef, &Font_7x10_0xef},
#else
  // character: 'п' == ''
  {0xef, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'р'
  {0xf0, &Font_7x10_0xf0},
#else
  // character: 'р' == ''
  {0xf0, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'с'
  {0xf1, &Font_7x10_0xf1},
#else
  // character: 'с' == ''
  {0xf1, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'т'
  {0xf2, &Font_7x10_0xf2},
#else
  // character: 'т' == ''
  {0xf2, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'у'
  {0xf3, &Font_7x10_0xf3},
#else
  // character: 'у' == ''
  {0xf3, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ф'
  {0xf4, &Font_7x10_0xf4},
#else
  // character: 'ф' == ''
  {0xf4, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'х'
  {0xf5, &Font_7x10_0xf5},
#else
  // character: 'х' == ''
  {0xf5, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ц'
  {0xf6, &Font_7x10_0xf6},
#else
  // character: 'ц' == ''
  {0xf6, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ч'
  {0xf7, &Font_7x10_0xf7},
#else
  // character: 'ч' == ''
  {0xf7, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ш'
  {0xf8, &Font_7x10_0xf8},
#else
  // character: 'ш' == ''
  {0xf8, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'щ'
  {0xf9, &Font_7x10_0xf9},
#else
  // character: 'щ' == ''
  {0xf9, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ъ'
  {0xfa, &Font_7x10_0xfa},
#else
  // character: 'ъ' == ''
  {0xfa, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ы'
  {0xfb, &Font_7x10_0xfb},
#else
  // character: 'ы' == ''
  {0xfb, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ь'
  {0xfc, &Font_7x10_0xfc},
#else
  // character: 'ь' == ''
  {0xfc, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'э'
  {0xfd, &Font_7x10_0xfd},
#else
  // character: 'э' == ''
  {0xfd, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'ю'
  {0xfe, &Font_7x10_0xfe},
#else
  // character: 'ю' == ''
  {0xfe, &Font_7x10_0x},
#endif

#if (0x0 == 0x0)
  // character: 'я'
  {0xff, &Font_7x10_0xff}
#else
  // character: 'я' == ''
  {0xff, &Font_7x10_0x}
#endif

};


const tFont Font_7x10 = { 167, Font_7x10_array };

