
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: C:/LW/bmp/lcd-image-converter/font16x18.xml
* name: Font_16x18
* family: Arial
* size: 22
* style: Black
* included characters: 0123456789:%
* antialiasing: no
* type: monospaced
* encoding: CP1251
* unicode bom: no
*
* preset name: Монохромное
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>
#include "bmp.h"



#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x25[32] = {
    // ##############
    // #∙∙∙∙#########
    // ∙∙##∙∙####∙∙##
    // ∙∙##∙∙####∙∙##
    // ∙∙##∙∙###∙∙###
    // ∙∙##∙∙###∙∙###
    // ∙∙##∙∙##∙∙####
    // #∙∙∙∙##∙∙∙####
    // ######∙∙######
    // ######∙∙######
    // ####∙∙∙##∙∙∙∙#
    // ####∙∙##∙∙##∙∙
    // ###∙∙###∙∙##∙∙
    // ###∙∙###∙∙##∙∙
    // ##∙∙####∙∙##∙∙
    // ##∙∙####∙∙##∙∙
    // #########∙∙∙∙#
    // ##############
    0x00, 0x01, 0xe0, 0x0c, 0xc3, 0x33, 0x0c, 0xcc, 0x63, 0x31, 0x8c, 0xcc, 0x1e, 0x70, 0x03, 0x00, 0x0c, 0x00, 0xe7, 0x83, 0x33, 0x18, 0xcc, 0x63, 0x33, 0x0c, 0xcc, 0x33, 0x00, 0x78, 0x00, 0x00
};
static const tImage Font_16x18_0x25 = { image_data_Font_16x18_0x25,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x30[32] = {
    // ##############
    // ####∙∙∙∙∙#####
    // ##∙∙∙∙∙∙∙∙∙###
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // #∙∙∙∙∙#∙∙∙∙∙##
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // #∙∙∙∙∙#∙∙∙∙∙##
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ##∙∙∙∙∙∙∙∙∙###
    // ####∙∙∙∙∙#####
    // ##############
    0x00, 0x00, 0x3e, 0x03, 0xfe, 0x1f, 0xfc, 0x7d, 0xf3, 0xe3, 0xef, 0x8f, 0xbe, 0x3e, 0xf8, 0xfb, 0xe3, 0xef, 0x8f, 0xbe, 0x3e, 0xf8, 0xf9, 0xf7, 0xc7, 0xff, 0x0f, 0xf8, 0x0f, 0x80, 0x00, 0x00
};
static const tImage Font_16x18_0x30 = { image_data_Font_16x18_0x30,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x31[32] = {
    // ##############
    // #######∙∙∙∙###
    // ######∙∙∙∙∙###
    // #####∙∙∙∙∙∙###
    // ###∙∙∙∙∙∙∙∙###
    // #∙∙∙∙∙∙∙∙∙∙###
    // #∙∙∙∙∙∙∙∙∙∙###
    // #∙∙∙##∙∙∙∙∙###
    // #∙####∙∙∙∙∙###
    // ######∙∙∙∙∙###
    // ######∙∙∙∙∙###
    // ######∙∙∙∙∙###
    // ######∙∙∙∙∙###
    // ######∙∙∙∙∙###
    // ######∙∙∙∙∙###
    // ######∙∙∙∙∙###
    // ######∙∙∙∙∙###
    // ##############
    0x00, 0x00, 0x07, 0x80, 0x3e, 0x01, 0xf8, 0x1f, 0xe1, 0xff, 0x87, 0xfe, 0x1c, 0xf8, 0x43, 0xe0, 0x0f, 0x80, 0x3e, 0x00, 0xf8, 0x03, 0xe0, 0x0f, 0x80, 0x3e, 0x00, 0xf8, 0x03, 0xe0, 0x00, 0x00
};
static const tImage Font_16x18_0x31 = { image_data_Font_16x18_0x31,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x32[32] = {
    // ##############
    // ###∙∙∙∙∙∙∙####
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // #∙∙∙∙∙∙∙∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ########∙∙∙∙∙#
    // #######∙∙∙∙∙∙#
    // ######∙∙∙∙∙∙##
    // #####∙∙∙∙∙∙###
    // ####∙∙∙∙∙∙####
    // ###∙∙∙∙∙######
    // ##∙∙∙∙∙#######
    // #∙∙∙∙∙∙∙∙∙∙∙∙#
    // #∙∙∙∙∙∙∙∙∙∙∙∙#
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙#
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙#
    // ##############
    0x00, 0x00, 0x7f, 0x07, 0xff, 0x1f, 0xfe, 0xf8, 0xfb, 0xe3, 0xe0, 0x0f, 0x80, 0x7e, 0x03, 0xf0, 0x1f, 0x80, 0xfc, 0x07, 0xc0, 0x3e, 0x01, 0xff, 0xe7, 0xff, 0xbf, 0xfe, 0xff, 0xf8, 0x00, 0x00
};
static const tImage Font_16x18_0x32 = { image_data_Font_16x18_0x32,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x33[32] = {
    // ##############
    // ###∙∙∙∙∙∙#####
    // ##∙∙∙∙∙∙∙∙∙###
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ∙∙∙∙∙##∙∙∙∙∙##
    // #∙∙∙∙##∙∙∙∙∙##
    // #######∙∙∙∙∙##
    // #####∙∙∙∙∙∙###
    // #####∙∙∙∙∙####
    // #####∙∙∙∙∙∙∙##
    // ########∙∙∙∙∙#
    // ########∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙∙##∙∙∙∙∙#
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ##∙∙∙∙∙∙∙∙∙###
    // ###∙∙∙∙∙∙∙####
    // ##############
    0x00, 0x00, 0x7e, 0x03, 0xfe, 0x1f, 0xfc, 0xf9, 0xf1, 0xe7, 0xc0, 0x1f, 0x01, 0xf8, 0x07, 0xc0, 0x1f, 0xc0, 0x0f, 0x80, 0x3e, 0xf8, 0xfb, 0xf3, 0xe7, 0xff, 0x0f, 0xf8, 0x1f, 0xc0, 0x00, 0x00
};
static const tImage Font_16x18_0x33 = { image_data_Font_16x18_0x33,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x34[32] = {
    // ##############
    // #######∙∙∙∙∙##
    // ######∙∙∙∙∙∙##
    // #####∙∙∙∙∙∙∙##
    // ####∙∙∙∙∙∙∙∙##
    // ###∙∙∙∙∙∙∙∙∙##
    // ###∙∙∙#∙∙∙∙∙##
    // ##∙∙∙##∙∙∙∙∙##
    // #∙∙∙###∙∙∙∙∙##
    // ∙∙∙####∙∙∙∙∙##
    // ∙∙∙####∙∙∙∙∙##
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // #######∙∙∙∙∙##
    // #######∙∙∙∙∙##
    // ##############
    0x00, 0x00, 0x07, 0xc0, 0x3f, 0x01, 0xfc, 0x0f, 0xf0, 0x7f, 0xc1, 0xdf, 0x0e, 0x7c, 0x71, 0xf3, 0x87, 0xce, 0x1f, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xc0, 0x7c, 0x01, 0xf0, 0x00, 0x00
};
static const tImage Font_16x18_0x34 = { image_data_Font_16x18_0x34,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x35[32] = {
    // ##############
    // ##∙∙∙∙∙∙∙∙∙∙##
    // ##∙∙∙∙∙∙∙∙∙∙##
    // ##∙∙∙∙∙∙∙∙∙∙##
    // ##∙∙∙∙∙∙∙∙∙∙##
    // #∙∙∙∙#########
    // #∙∙∙∙#∙∙∙∙####
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // #∙∙∙∙##∙∙∙∙∙∙#
    // ########∙∙∙∙∙#
    // ########∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙∙#∙∙∙∙∙∙#
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ##∙∙∙∙∙∙∙∙∙###
    // ###∙∙∙∙∙∙∙####
    // ##############
    0x00, 0x00, 0xff, 0xc3, 0xff, 0x0f, 0xfc, 0x3f, 0xf1, 0xe0, 0x07, 0xbc, 0x1f, 0xfc, 0x7f, 0xf1, 0xe7, 0xe0, 0x0f, 0x80, 0x3e, 0xf8, 0xfb, 0xf7, 0xe7, 0xff, 0x0f, 0xf8, 0x1f, 0xc0, 0x00, 0x00
};
static const tImage Font_16x18_0x35 = { image_data_Font_16x18_0x35,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x36[32] = {
    // ##############
    // ####∙∙∙∙∙∙####
    // ##∙∙∙∙∙∙∙∙∙###
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // #∙∙∙∙∙##∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙##
    // ∙∙∙∙∙#########
    // ∙∙∙∙∙#∙∙∙∙####
    // ∙∙∙∙∙∙∙∙∙∙∙∙##
    // ∙∙∙∙∙∙∙∙∙∙∙∙##
    // ∙∙∙∙∙∙##∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // #∙∙∙∙∙##∙∙∙∙∙#
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ##∙∙∙∙∙∙∙∙∙∙##
    // ####∙∙∙∙∙∙####
    // ##############
    0x00, 0x00, 0x3f, 0x03, 0xfe, 0x1f, 0xfc, 0x7c, 0xfb, 0xe3, 0xcf, 0x80, 0x3e, 0xf0, 0xff, 0xf3, 0xff, 0xcf, 0xcf, 0xbe, 0x3e, 0xf8, 0xf9, 0xf3, 0xe7, 0xff, 0x0f, 0xfc, 0x0f, 0xc0, 0x00, 0x00
};
static const tImage Font_16x18_0x36 = { image_data_Font_16x18_0x36,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x37[32] = {
    // ##############
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙#
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙#
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙#
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙#
    // #########∙∙∙##
    // ########∙∙∙###
    // #######∙∙∙∙###
    // ######∙∙∙∙####
    // ######∙∙∙∙####
    // #####∙∙∙∙#####
    // #####∙∙∙∙#####
    // ####∙∙∙∙∙#####
    // ####∙∙∙∙######
    // ####∙∙∙∙######
    // ###∙∙∙∙∙######
    // ###∙∙∙∙∙######
    // ##############
    0x00, 0x03, 0xff, 0xef, 0xff, 0xbf, 0xfe, 0xff, 0xf8, 0x01, 0xc0, 0x0e, 0x00, 0x78, 0x03, 0xc0, 0x0f, 0x00, 0x78, 0x01, 0xe0, 0x0f, 0x80, 0x3c, 0x00, 0xf0, 0x07, 0xc0, 0x1f, 0x00, 0x00, 0x00
};
static const tImage Font_16x18_0x37 = { image_data_Font_16x18_0x37,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x38[32] = {
    // ##############
    // ###∙∙∙∙∙∙∙####
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ###∙∙∙∙∙∙∙####
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ###∙∙∙∙∙∙∙####
    // ##############
    0x00, 0x00, 0x7f, 0x07, 0xff, 0x3f, 0xfe, 0xf8, 0xfb, 0xe3, 0xef, 0x8f, 0x9f, 0xfc, 0x1f, 0xc1, 0xff, 0xcf, 0x8f, 0xbe, 0x3e, 0xf8, 0xfb, 0xe3, 0xe7, 0xff, 0x1f, 0xfc, 0x1f, 0xc0, 0x00, 0x00
};
static const tImage Font_16x18_0x38 = { image_data_Font_16x18_0x38,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x39[32] = {
    // ##############
    // ###∙∙∙∙∙∙#####
    // #∙∙∙∙∙∙∙∙∙∙###
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ∙∙∙∙∙##∙∙∙∙∙##
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙##∙∙∙∙∙∙#
    // #∙∙∙∙∙∙∙∙∙∙∙∙#
    // #∙∙∙∙∙∙∙∙∙∙∙∙#
    // ###∙∙∙∙#∙∙∙∙∙#
    // ########∙∙∙∙∙#
    // #∙∙∙∙###∙∙∙∙∙#
    // ∙∙∙∙∙##∙∙∙∙∙##
    // #∙∙∙∙∙∙∙∙∙∙∙##
    // ##∙∙∙∙∙∙∙∙∙###
    // ###∙∙∙∙∙∙#####
    // ##############
    0x00, 0x00, 0x7e, 0x07, 0xfe, 0x1f, 0xfc, 0xf9, 0xf3, 0xe3, 0xef, 0x8f, 0xbe, 0x7e, 0x7f, 0xf9, 0xff, 0xe1, 0xef, 0x80, 0x3e, 0x78, 0xfb, 0xe7, 0xc7, 0xff, 0x0f, 0xf8, 0x1f, 0x80, 0x00, 0x00
};
static const tImage Font_16x18_0x39 = { image_data_Font_16x18_0x39,
    14, 18};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_16x18_0x3a[32] = {
    // ##############
    // ##############
    // ##############
    // ##############
    // ##############
    // ####∙∙∙∙∙#####
    // ####∙∙∙∙∙#####
    // ####∙∙∙∙∙#####
    // ####∙∙∙∙∙#####
    // ####∙∙∙∙∙#####
    // ##############
    // ##############
    // ####∙∙∙∙∙#####
    // ####∙∙∙∙∙#####
    // ####∙∙∙∙∙#####
    // ####∙∙∙∙∙#####
    // ####∙∙∙∙∙#####
    // ##############
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3e, 0x00, 0xf8, 0x03, 0xe0, 0x0f, 0x80, 0x3e, 0x00, 0x00, 0x00, 0x00, 0x0f, 0x80, 0x3e, 0x00, 0xf8, 0x03, 0xe0, 0x0f, 0x80, 0x00, 0x00
};
static const tImage Font_16x18_0x3a = { image_data_Font_16x18_0x3a,
    14, 18};
#endif


static const tChar Font_16x18_array[] = {

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Font_16x18_0x25},
#else
  // character: '%' == ''
  {0x25, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font_16x18_0x30},
#else
  // character: '0' == ''
  {0x30, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font_16x18_0x31},
#else
  // character: '1' == ''
  {0x31, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font_16x18_0x32},
#else
  // character: '2' == ''
  {0x32, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font_16x18_0x33},
#else
  // character: '3' == ''
  {0x33, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font_16x18_0x34},
#else
  // character: '4' == ''
  {0x34, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font_16x18_0x35},
#else
  // character: '5' == ''
  {0x35, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font_16x18_0x36},
#else
  // character: '6' == ''
  {0x36, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font_16x18_0x37},
#else
  // character: '7' == ''
  {0x37, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font_16x18_0x38},
#else
  // character: '8' == ''
  {0x38, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font_16x18_0x39},
#else
  // character: '9' == ''
  {0x39, &Font_16x18_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Font_16x18_0x3a}
#else
  // character: ':' == ''
  {0x3a, &Font_16x18_0x}
#endif

};


const tFont Font_16x18 = { 12, Font_16x18_array };

