
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: C:/LW/bmp/lcd-image-converter/img_top.xml
* name: img_top
*
* preset name: Монохромное
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize; , 8
     } tImage;
*/
#include <stdint.h>
#include "bmp.h"




static const uint8_t image_data_img_top[11] = {
    // #####∙#####
    // ####∙∙∙####
    // ###∙∙∙∙∙###
    // ##∙∙∙#∙∙∙##
    // #∙∙∙###∙∙∙#
    // ∙∙∙#####∙∙∙
    // ∙∙#######∙∙
    // ###########
    0x04, 0x01, 0xc0, 0x7c, 0x1d, 0xc7, 0x1d, 0xc1, 0xf0, 0x18, 0x00
};
const tImage img_top = { image_data_img_top, 11, 8};

