
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: C:/LW/bmp/lcd-image-converter/img_key_del.xml
* name: img_key_del
*
* preset name: Монохромное
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize; , 8
     } tImage;
*/
#include <stdint.h>
#include "bmp.h"




static const uint8_t image_data_img_key_del[9] = {
    // ##########
    // ###∙######
    // ##∙#######
    // #∙∙∙∙∙∙∙∙#
    // ##∙#######
    // ###∙######
    // ##########
    0x00, 0x04, 0x02, 0x01, 0xfe, 0x20, 0x04, 0x00, 0x00
};
const tImage img_key_del = { image_data_img_key_del, 10, 7};

