
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: C:/LW/bmp/lcd-image-converter/img_rssi0.xml
* name: img_rssi0
*
* preset name: Монохромное
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize; , 8
     } tImage;
*/
#include <stdint.h>
#include "bmp.h"




static const uint8_t image_data_img_rssi0[24] = {
    // ###########################
    // ###########################
    // ##∙###∙#∙#∙∙∙∙#∙###∙###∙###
    // ##∙###∙###∙#########∙#∙####
    // ##∙###∙#∙#∙∙∙##∙#####∙#####
    // ##∙#∙#∙#∙#∙####∙####∙#∙####
    // ###∙#∙##∙#∙####∙###∙###∙###
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8a, 0xf4, 0x44, 0x11, 0x10, 0x05, 0x02, 0x2b, 0x90, 0x40, 0x55, 0x42, 0x14, 0x05, 0x28, 0x44, 0x40
};
const tImage img_rssi0 = { image_data_img_rssi0, 27, 7};

