
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: C:/LW/bmp/lcd-image-converter/img_bat2.xml
* name: img_bat2
*
* preset name: Монохромное
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize; , 8
     } tImage;
*/
#include <stdint.h>
#include "bmp.h"




static const uint8_t image_data_img_bat2[10] = {
    // ###########
    // ###########
    // ∙∙∙∙∙∙∙∙###
    // ∙∙∙####∙∙##
    // ∙∙∙####∙∙##
    // ∙∙∙####∙∙##
    // ∙∙∙∙∙∙∙∙###
    0x00, 0x00, 0x03, 0xfc, 0x70, 0xce, 0x19, 0xc3, 0x3f, 0xc0
};
const tImage img_bat2 = { image_data_img_bat2, 11, 7};

